In [1]:
import os
import sys
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import torch

project_dir = os.path.dirname(os.path.dirname(os.path.abspath('__file__')))
sys.path.append(project_dir)
from raw_data_processing import get_x, get_y, get_wavelength
from tools import JSON_Read#, plotly_multi_scatter
from tools import KAN_es_2 as KAN_es
from tools import lmdKAN_es
SCRIPT_DIR = os.path.abspath('')


def get_sqz_input(x_axis, y_axis):
    ''' Evaluate squeezed data from curve.
    '''
    i_max = np.argmax(y_axis)
    I = y_axis[i_max]  # Max I
    c_I = x_axis[i_max]  # Coordinate of max I

    diff_I = np.absolute(y_axis-I/2)
    c_I2_left = x_axis[ np.argmin(diff_I[:i_max]) ]  # Left I/2 coordinate
    c_I2_right = x_axis[ np.argmin(diff_I[i_max:])+i_max]  # Right I/2 coordinate

    c_I2 = np.mean([c_I2_left, c_I2_right])  # Mean center coordinate on I/2 
    disp_I2 = np.abs(c_I2_right-c_I2_left)  # Width of curve on I/2 y-level

    integr_ratio = np.sum(y_axis[i_max+1:]) / np.sum(y_axis[:i_max])

    sqz_input = [I, c_I, c_I2, disp_I2, integr_ratio]
    
    
    return sqz_input

def get_all_sqz_input(matr_x, matr_y):
    matr_sqz_input = []
    for x_axis, y_axis in zip(matr_x, matr_y):
        matr_sqz_input.append(get_sqz_input(x_axis, y_axis))


    return np.array(matr_sqz_input)


d_config = JSON_Read("", "json_config.txt")
EXCITE_WAVE_LENGTH = d_config['EXCITE_WAVE_LENGTH']
#PREDICT_IONS = ['Cr']# ['Cr'], ['Cu'], ['Ni'], ['NO3']# d_config['PREDICT_IONS']
SPEC_FOLDER = d_config['SPEC_FOLDER']

TRAIN_TEST_RATIO = d_config['TRAIN_TEST_RATIO']
VALIDATION_TRAIN_RATIO = d_config['VALIDATION_TRAIN_RATIO']
N_ITER_NO_CHANGE = d_config['N_ITER_NO_CHANGE']

HIDDEN_LAYER_SIZES = d_config['HIDDEN_LAYER_SIZES']
ACTIVATION = d_config['ACTIVATION']
SOLVER = d_config['SOLVER']
MAX_ITER = d_config['MAX_ITER']
TOL = d_config['TOL']

x = get_x(wave_length=EXCITE_WAVE_LENGTH, spec_file=project_dir+'\\'+SPEC_FOLDER)

y_Cr = get_y(l_ions='Cr', spec_file=project_dir+'\\'+SPEC_FOLDER)
y_Cu = get_y(l_ions='Cu', spec_file=project_dir+'\\'+SPEC_FOLDER)
y_Ni = get_y(l_ions='Ni', spec_file=project_dir+'\\'+SPEC_FOLDER)
y_NO3 = get_y(l_ions='NO3', spec_file=project_dir+'\\'+SPEC_FOLDER)

l_wavelenth = get_wavelength(spec_file=project_dir+'\\'+SPEC_FOLDER)

x_matrix, y_matrix = np.broadcast_to(l_wavelenth, (len(x), len(l_wavelenth))), x.to_numpy()
x = get_all_sqz_input(x_matrix, y_matrix)

In [2]:
from sklearn.base import RegressorMixin, BaseEstimator, _fit_context
from sklearn.utils.validation import check_is_fitted


class KANRegressor(RegressorMixin, BaseEstimator):
    """Sci-kit learn wrapper for pykan model.
    
    Hierarchical inheritance chain of classes:
    1. pykan.kan --> 
    2. --> KAN_es: pykan.kan with early stopping, made as in skl.neural_network.MLPRegressor -->
    3. --> KANRegressor: pykan.kan wrapped in (RegressorMixin, BaseEstimator) for compatibility with skl interface.
           Uses params, inspired by skl.neural_network.MLPRegressor params logic.
    """

    # This is a dictionary allowing to define the type of parameters.
    # It used to validate parameter within the `_fit_context` decorator.
    
    _parameter_constraints = {}
    
    _d_solver_translation = {
        'lbfgs': 'LBFGS',
        'adam': 'Adam'
    }

    def __init__(self, 
                 # kan.__init__ args
                 hidden_layer_sizes=None,
                 grid=3,
                 k=3,
                 seed=1,
                 device='cpu',
                 # kan.train_es args
                 tol=1e-3,
                 n_iter_no_change=10,
                 solver='lbfgs',
                 max_iter=100,
                 learning_rate_init=1.0,
                 validation_fraction=0.1,
                 # additional kan.__init__ args
                 mult_arity = 2, noise_scale=0.3, scale_base_mu=0.0, scale_base_sigma=1.0, base_fun='silu', symbolic_enabled=True, affine_trainable=False, grid_eps=0.02, grid_range=[-1, 1], sp_trainable=True, sb_trainable=True, save_act=True, sparse_init=False, auto_save=True, first_init=True, ckpt_path='./model', state_id=0, round=0,
                 # additional kan.train_es args
                 log=1, lamb=0., lamb_l1=1., lamb_entropy=2., lamb_coef=0., lamb_coefdiff=0., update_grid=True, grid_update_num=10, loss_fn=None, start_grid_update_step=-1, stop_grid_update_step=50, batch=-1, metrics=None, singularity_avoiding=False, save_fig=False, in_vars=None, out_vars=None, beta=3, save_fig_freq=1, img_folder='./video',  y_th=1000., reg_metric='edge_forward_spline_n', display_metrics=None
                 ):
        '''
        Init method. Saving all kan.__init__ and kan.fit args.
        
        Args:
        -----
            -- kan.__init__ parameteres --
            hidden_layer_sizes : list
                the ith element represents the number of neurons in the ith hidden layer.
            grid : int
                number of grid intervals. Default: 3.
            k : int
                order of piecewise polynomial. Default: 3.
            mult_arity : int, or list of int lists
                multiplication arity for each multiplication node (the number of numbers to be multiplied)
            noise_scale : float
                initial injected noise to spline.
            base_fun : str
                the residual function b(x). Default: 'silu'
            symbolic_enabled : bool
                compute (True) or skip (False) symbolic computations (for efficiency). By default: True. 
            affine_trainable : bool
                affine parameters are updated or not. Affine parameters include node_scale, node_bias, subnode_scale, subnode_bias
            grid_eps : float
                When grid_eps = 1, the grid is uniform; when grid_eps = 0, the grid is partitioned using percentiles of samples. 0 < grid_eps < 1 interpolates between the two extremes.
            grid_range : list/np.array of shape (2,))
                setting the range of grids. Default: [-1,1]. This argument is not important if fit(update_grid=True) (by default updata_grid=True)
            sp_trainable : bool
                If true, scale_sp is trainable. Default: True.
            sb_trainable : bool
                If true, scale_base is trainable. Default: True.
            device : str
                device
            seed : int
                random seed
            save_act : bool
                indicate whether intermediate activations are saved in forward pass
            sparse_init : bool
                sparse initialization (True) or normal dense initialization. Default: False.
            auto_save : bool
                indicate whether to automatically save a checkpoint once the model is modified
            state_id : int
                the state of the model (used to save checkpoint)
            ckpt_path : str
                the folder to store checkpoints. Default: './model'
            round : int
                the number of times rewind() has been called
            
            -- kan.train_es parameteres --
            tol : float
                Delta of validation fit which doesn`t count as fitness improvement. (Tolerence of training).
            n_iter_no_change : int
                Number of iteration with no fit change to early stopping.
            solver : str
                "lbfgs" or "adam"
            max_iter : int
                training steps
            learning_rate_init: float
                learning rate
            log : int
                logging frequency
            lamb : float
                overall penalty strength
            lamb_l1 : float
                l1 penalty strength
            lamb_entropy : float
                entropy penalty strength
            lamb_coef : float
                coefficient magnitude penalty strength
            lamb_coefdiff : float
                difference of nearby coefficits (smoothness) penalty strength
            update_grid : bool
                If True, update grid regularly before stop_grid_update_step
            grid_update_num : int
                the number of grid updates before stop_grid_update_step
            stop_grid_update_step : int
                no grid updates after this training step
            batch : int
                batch size, if -1 then full.
            small_mag_threshold : float
                threshold to determine large or small numbers (may want to apply larger penalty to smaller numbers)
            small_reg_factor : float
                penalty strength applied to small factors relative to large factos
            save_fig_freq : int
                save figure every (save_fig_freq) step
        '''
        
        self.hidden_layer_sizes, self.grid, self.k, self.seed, self.device = hidden_layer_sizes, grid, k, seed, device
        self.mult_arity, self.noise_scale, self.scale_base_mu, self.scale_base_sigma, self.base_fun, self.symbolic_enabled, self.affine_trainable, self.grid_eps, self.grid_range, self.sp_trainable, self.sb_trainable, self.save_act, self.sparse_init, self.auto_save, self.first_init, self.ckpt_path, self.state_id, self.round = mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, save_act, sparse_init, auto_save, first_init, ckpt_path, state_id, round
        
        self.tol, self.n_iter_no_change, self.solver, self.max_iter, self.learning_rate_init, self.validation_fraction = tol, n_iter_no_change, solver, max_iter, learning_rate_init, validation_fraction
        self.log, self.lamb, self.lamb_l1, self.lamb_entropy, self.lamb_coef, self.lamb_coefdiff, self.update_grid, self.grid_update_num, self.loss_fn, self.start_grid_update_step, self.stop_grid_update_step, self.batch, self.metrics, self.singularity_avoiding, self.save_fig, self.in_vars, self.out_vars, self.beta, self.save_fig_freq, self.img_folder, self.y_th, self.reg_metric, self.display_metrics = log, lamb, lamb_l1, lamb_entropy, lamb_coef, lamb_coefdiff, update_grid, grid_update_num, loss_fn, start_grid_update_step, stop_grid_update_step, batch, metrics, singularity_avoiding, save_fig, in_vars, out_vars, beta, save_fig_freq, img_folder, y_th, reg_metric, display_metrics
        
    @_fit_context(prefer_skip_nested_validation=True)
    def fit(self, X, y, speed=False):
        """A reference implementation of a fitting function.

        Parameters
        ----------
        X : {array-like, sparse matrix}, shape (n_samples, n_features)
            The training input samples.

        y : array-like, shape (n_samples,) or (n_samples, n_outputs)
            The target values (class labels in classification, real numbers in
            regression).

        Returns
        -------
        self : object
            Returns self.
        """
        # `_validate_data` is defined in the `BaseEstimator` class.
        # It allows to:
        # - run different checks on the input data;
        # - define some attributes associated to the input data: `n_features_in_` and
        #   `feature_names_in_`.
        
        # Make sure self.hidden_layer_sizes is a list
        hidden_layer_sizes = self.hidden_layer_sizes
        if not hasattr(hidden_layer_sizes, "__iter__"):
            hidden_layer_sizes = [hidden_layer_sizes]
        hidden_layer_sizes = list(hidden_layer_sizes)
        
        X, y = self._validate_data(X, y, accept_sparse=True)
        n_features = X.shape[1]
        
        # Ensure y is 2D
        if y.ndim == 1:
            y = y.reshape((-1, 1))
            
        if not hasattr(self, "is_fitted_"): self.is_fitted_ = False
        
        if not self.is_fitted_:
            self.n_outputs_ = y.shape[1]
        
            self.width = [n_features] + self.hidden_layer_sizes + [self.n_outputs_]
            self.kan = KAN_es(width=self.width, grid=self.grid, k=self.k, seed=self.seed, device=self.device,
                              mult_arity=self.mult_arity, noise_scale=self.noise_scale, scale_base_mu=self.scale_base_mu, scale_base_sigma=self.scale_base_sigma, base_fun=self.base_fun, symbolic_enabled=self.symbolic_enabled, affine_trainable=self.affine_trainable, grid_eps=self.grid_eps, grid_range=self.grid_range, sp_trainable=self.sp_trainable, sb_trainable=self.sb_trainable, save_act=self.save_act, sparse_init=self.sparse_init, auto_save=self.auto_save, first_init=self.first_init, ckpt_path=self.ckpt_path, state_id=self.state_id, round=self.round)
        
        if speed: self.kan.speed()
        
        X_train, X_val, y_train, y_val = train_test_split(X, y, 
                                                        test_size=self.validation_fraction,
                                                        random_state=self.seed)
                    
        kan_dataset = {'train_input': torch.tensor(np.array(X_train), dtype=torch.float),
                       'train_label': torch.tensor(np.array(y_train), dtype=torch.float),
                       'test_input': torch.tensor(np.array(X_val), dtype=torch.float),
                       'test_label': torch.tensor(np.array(y_val), dtype=torch.float)}
        
        results = self.kan.fit(kan_dataset, 
                               tol=self.tol, 
                               n_iter_no_change=self.n_iter_no_change,
                               opt=self._d_solver_translation[self.solver], 
                               lr = self.learning_rate_init,
                               steps=self.max_iter,
                               log=self.log, lamb=self.lamb, lamb_l1=self.lamb_l1, lamb_entropy=self.lamb_entropy, lamb_coef=self.lamb_coef, lamb_coefdiff=self.lamb_coefdiff, update_grid=self.update_grid, grid_update_num=self.grid_update_num, loss_fn=self.loss_fn, stop_grid_update_step=self.stop_grid_update_step, batch=self.batch, singularity_avoiding=self.singularity_avoiding, save_fig=self.save_fig, in_vars=self.in_vars, out_vars=self.out_vars, beta=self.beta, save_fig_freq=self.save_fig_freq, img_folder=self.img_folder, y_th=self.y_th, reg_metric=self.reg_metric, display_metrics=self.display_metrics
                                )
        
        self. kan.results = results
        self.is_fitted_ = True
        # `fit` should always return `self`
        return self

    def predict(self, X):
        """A reference implementation of a predicting function.

        Parameters
        ----------
        X : {array-like, sparse matrix}, shape (n_samples, n_features)
            The training input samples.

        Returns
        -------
        y : ndarray of shape (n_samples, n_outputs)
            The predicted values.
        """
        # Check if fit had been called
        check_is_fitted(self)
        # We need to set reset=False because we don't want to overwrite `n_features_in_`
        # `feature_names_in_` but only check that the shape is consistent.
        X = self._validate_data(X, accept_sparse=True, reset=False)
        
        x = torch.tensor(np.array(X), dtype=torch.float)
        pred = self.kan.forward(x).detach().numpy()
        
        return pred
    

class lmdKANRegressor(RegressorMixin, BaseEstimator):
    """Sci-kit learn wrapper for pykan model.
    
    Hierarchical inheritance chain of classes:
    1. pykan.kan --> 
    2. --> KAN_es: pykan.kan with early stopping, made as in skl.neural_network.MLPRegressor -->
    3. --> KANRegressor: pykan.kan wrapped in (RegressorMixin, BaseEstimator) for compatibility with skl interface.
           Uses params, inspired by skl.neural_network.MLPRegressor params logic.
    """

    # This is a dictionary allowing to define the type of parameters.
    # It used to validate parameter within the `_fit_context` decorator.
    
    _parameter_constraints = {}
    
    _d_solver_translation = {
        'lbfgs': 'LBFGS',
        'adam': 'Adam'
    }

    def __init__(self, 
                 # kan.__init__ args
                 hidden_layer_sizes=None,
                 grid=3,
                 k=3,
                 seed=1,
                 device='cpu',
                 # kan.train_es args
                 tol=1e-3,
                 n_iter_no_change=10,
                 solver='lbfgs',
                 max_iter=100,
                 learning_rate_init=1.0,
                 validation_fraction=0.1,
                 # additional kan.__init__ args
                 mult_arity = 2, noise_scale=0.3, scale_base_mu=0.0, scale_base_sigma=1.0, base_fun='silu', symbolic_enabled=True, affine_trainable=False, grid_eps=0.02, grid_range=[-1, 1], sp_trainable=True, sb_trainable=True, save_act=True, sparse_init=False, auto_save=True, first_init=True, ckpt_path='./model', state_id=0, round=0,
                 lmd_init_vector=None, lmd_init_mu=0.0, lmd_init_sigma=1.0, lmd_trainable=True,
                 # additional kan.train_es args
                 log=1, lamb=0., lamb_l1=1., lamb_entropy=2., lamb_coef=0., lamb_coefdiff=0., update_grid=True, grid_update_num=10, loss_fn=None, start_grid_update_step=-1, stop_grid_update_step=50, batch=-1, metrics=None, singularity_avoiding=False, save_fig=False, in_vars=None, out_vars=None, beta=3, save_fig_freq=1, img_folder='./video',  y_th=1000., reg_metric='edge_forward_spline_n', display_metrics=None
                 ):
        '''
        Init method. Saving all kan.__init__ and kan.fit args.
        
        Args:
        -----
            -- kan.__init__ parameteres --
            hidden_layer_sizes : list
                the ith element represents the number of neurons in the ith hidden layer.
            grid : int
                number of grid intervals. Default: 3.
            k : int
                order of piecewise polynomial. Default: 3.
            mult_arity : int, or list of int lists
                multiplication arity for each multiplication node (the number of numbers to be multiplied)
            noise_scale : float
                initial injected noise to spline.
            base_fun : str
                the residual function b(x). Default: 'silu'
            symbolic_enabled : bool
                compute (True) or skip (False) symbolic computations (for efficiency). By default: True. 
            affine_trainable : bool
                affine parameters are updated or not. Affine parameters include node_scale, node_bias, subnode_scale, subnode_bias
            grid_eps : float
                When grid_eps = 1, the grid is uniform; when grid_eps = 0, the grid is partitioned using percentiles of samples. 0 < grid_eps < 1 interpolates between the two extremes.
            grid_range : list/np.array of shape (2,))
                setting the range of grids. Default: [-1,1]. This argument is not important if fit(update_grid=True) (by default updata_grid=True)
            sp_trainable : bool
                If true, scale_sp is trainable. Default: True.
            sb_trainable : bool
                If true, scale_base is trainable. Default: True.
            device : str
                device
            seed : int
                random seed
            save_act : bool
                indicate whether intermediate activations are saved in forward pass
            sparse_init : bool
                sparse initialization (True) or normal dense initialization. Default: False.
            auto_save : bool
                indicate whether to automatically save a checkpoint once the model is modified
            state_id : int
                the state of the model (used to save checkpoint)
            ckpt_path : str
                the folder to store checkpoints. Default: './model'
            round : int
                the number of times rewind() has been called
            
            -- kan.train_es parameteres --
            tol : float
                Delta of validation fit which doesn`t count as fitness improvement. (Tolerence of training).
            n_iter_no_change : int
                Number of iteration with no fit change to early stopping.
            solver : str
                "lbfgs" or "adam"
            max_iter : int
                training steps
            learning_rate_init: float
                learning rate
            log : int
                logging frequency
            lamb : float
                overall penalty strength
            lamb_l1 : float
                l1 penalty strength
            lamb_entropy : float
                entropy penalty strength
            lamb_coef : float
                coefficient magnitude penalty strength
            lamb_coefdiff : float
                difference of nearby coefficits (smoothness) penalty strength
            update_grid : bool
                If True, update grid regularly before stop_grid_update_step
            grid_update_num : int
                the number of grid updates before stop_grid_update_step
            stop_grid_update_step : int
                no grid updates after this training step
            batch : int
                batch size, if -1 then full.
            small_mag_threshold : float
                threshold to determine large or small numbers (may want to apply larger penalty to smaller numbers)
            small_reg_factor : float
                penalty strength applied to small factors relative to large factos
            save_fig_freq : int
                save figure every (save_fig_freq) step
        '''
        
        self.hidden_layer_sizes, self.grid, self.k, self.seed, self.device = hidden_layer_sizes, grid, k, seed, device
        self.mult_arity, self.noise_scale, self.scale_base_mu, self.scale_base_sigma, self.base_fun, self.symbolic_enabled, self.affine_trainable, self.grid_eps, self.grid_range, self.sp_trainable, self.sb_trainable, self.save_act, self.sparse_init, self.auto_save, self.first_init, self.ckpt_path, self.state_id, self.round = mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, save_act, sparse_init, auto_save, first_init, ckpt_path, state_id, round
        self.lmd_init_vector, self.lmd_init_mu, self.lmd_init_sigma, self.lmd_trainable = lmd_init_vector, lmd_init_mu, lmd_init_sigma, lmd_trainable
        
        self.tol, self.n_iter_no_change, self.solver, self.max_iter, self.learning_rate_init, self.validation_fraction = tol, n_iter_no_change, solver, max_iter, learning_rate_init, validation_fraction
        self.log, self.lamb, self.lamb_l1, self.lamb_entropy, self.lamb_coef, self.lamb_coefdiff, self.update_grid, self.grid_update_num, self.loss_fn, self.start_grid_update_step, self.stop_grid_update_step, self.batch, self.metrics, self.singularity_avoiding, self.save_fig, self.in_vars, self.out_vars, self.beta, self.save_fig_freq, self.img_folder, self.y_th, self.reg_metric, self.display_metrics = log, lamb, lamb_l1, lamb_entropy, lamb_coef, lamb_coefdiff, update_grid, grid_update_num, loss_fn, start_grid_update_step, stop_grid_update_step, batch, metrics, singularity_avoiding, save_fig, in_vars, out_vars, beta, save_fig_freq, img_folder, y_th, reg_metric, display_metrics
        
    @_fit_context(prefer_skip_nested_validation=True)
    def fit(self, X, y, speed=False):
        """A reference implementation of a fitting function.

        Parameters
        ----------
        X : {array-like, sparse matrix}, shape (n_samples, n_features)
            The training input samples.

        y : array-like, shape (n_samples,) or (n_samples, n_outputs)
            The target values (class labels in classification, real numbers in
            regression).

        Returns
        -------
        self : object
            Returns self.
        """
        # `_validate_data` is defined in the `BaseEstimator` class.
        # It allows to:
        # - run different checks on the input data;
        # - define some attributes associated to the input data: `n_features_in_` and
        #   `feature_names_in_`.
        
        # Make sure self.hidden_layer_sizes is a list
        hidden_layer_sizes = self.hidden_layer_sizes
        if not hasattr(hidden_layer_sizes, "__iter__"):
            hidden_layer_sizes = [hidden_layer_sizes]
        hidden_layer_sizes = list(hidden_layer_sizes)
        
        X, y = self._validate_data(X, y, accept_sparse=True)
        n_features = X.shape[1]
        
        # Ensure y is 2D
        if y.ndim == 1:
            y = y.reshape((-1, 1))
            
        if not hasattr(self, "is_fitted_"): self.is_fitted_ = False
        
        if not self.is_fitted_:
            self.n_outputs_ = y.shape[1]
        
            self.width = [n_features] + self.hidden_layer_sizes + [self.n_outputs_]
            self.kan = lmdKAN_es(width=self.width, grid=self.grid, k=self.k, seed=self.seed, device=self.device,
                                 mult_arity=self.mult_arity, noise_scale=self.noise_scale, scale_base_mu=self.scale_base_mu, scale_base_sigma=self.scale_base_sigma, base_fun=self.base_fun, symbolic_enabled=self.symbolic_enabled, affine_trainable=self.affine_trainable, grid_eps=self.grid_eps, grid_range=self.grid_range, sp_trainable=self.sp_trainable, sb_trainable=self.sb_trainable, save_act=self.save_act, sparse_init=self.sparse_init, auto_save=self.auto_save, first_init=self.first_init, ckpt_path=self.ckpt_path, state_id=self.state_id, round=self.round,
                                 lmd_init_vector=self.lmd_init_vector, lmd_init_mu=self.lmd_init_mu, lmd_init_sigma=self.lmd_init_sigma, lmd_trainable=self.lmd_trainable)
        
        if speed: self.kan.speed()
        
        X_train, X_val, y_train, y_val = train_test_split(X, y, 
                                                        test_size=self.validation_fraction,
                                                        random_state=self.seed)
                    
        kan_dataset = {'train_input': torch.tensor(np.array(X_train), dtype=torch.float),
                       'train_label': torch.tensor(np.array(y_train), dtype=torch.float),
                       'test_input': torch.tensor(np.array(X_val), dtype=torch.float),
                       'test_label': torch.tensor(np.array(y_val), dtype=torch.float)}
        
        results = self.kan.fit(kan_dataset, 
                               tol=self.tol, 
                               n_iter_no_change=self.n_iter_no_change,
                               opt=self._d_solver_translation[self.solver], 
                               lr = self.learning_rate_init,
                               steps=self.max_iter,
                               log=self.log, lamb=self.lamb, lamb_l1=self.lamb_l1, lamb_entropy=self.lamb_entropy, lamb_coef=self.lamb_coef, lamb_coefdiff=self.lamb_coefdiff, update_grid=self.update_grid, grid_update_num=self.grid_update_num, loss_fn=self.loss_fn, stop_grid_update_step=self.stop_grid_update_step, batch=self.batch, singularity_avoiding=self.singularity_avoiding, save_fig=self.save_fig, in_vars=self.in_vars, out_vars=self.out_vars, beta=self.beta, save_fig_freq=self.save_fig_freq, img_folder=self.img_folder, y_th=self.y_th, reg_metric=self.reg_metric, display_metrics=self.display_metrics
                                )
        
        self. kan.results = results
        self.is_fitted_ = True
        # `fit` should always return `self`
        return self

    def predict(self, X):
        """A reference implementation of a predicting function.

        Parameters
        ----------
        X : {array-like, sparse matrix}, shape (n_samples, n_features)
            The training input samples.

        Returns
        -------
        y : ndarray of shape (n_samples, n_outputs)
            The predicted values.
        """
        # Check if fit had been called
        check_is_fitted(self)
        # We need to set reset=False because we don't want to overwrite `n_features_in_`
        # `feature_names_in_` but only check that the shape is consistent.
        X = self._validate_data(X, accept_sparse=True, reset=False)
        
        x = torch.tensor(np.array(X), dtype=torch.float)
        pred = self.kan.forward(x).detach().numpy()
        
        return pred

## Loading data

In [3]:
def alg_sklMLP_model(x, y, class_model, model_kwargs, seed = None):
    
    x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                        train_size=TRAIN_TEST_RATIO,
                                                        random_state=seed)
    
    scaler = StandardScaler()
    x_train = scaler.fit_transform(x_train)
    x_test = scaler.transform(x_test)

    #print(model_kwargs)
    model = class_model(random_state=seed, **model_kwargs)
    model.fit(x_train, y_train)

    pred_test = model.predict(x_test)
    rmse = mean_squared_error(y_test, pred_test)
    r2 = r2_score(y_test, pred_test)
    mae = mean_absolute_error(y_test, pred_test)
    
    del model

    return [rmse, r2, mae]

def alg_sklKAN_model(x, y, class_model, model_kwargs, seed = None):
    
    x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                        train_size=TRAIN_TEST_RATIO,
                                                        random_state=seed)
    
    scaler = StandardScaler()
    x_train = scaler.fit_transform(x_train)
    x_test = scaler.transform(x_test)

    #print(model_kwargs)
    model = class_model(seed=seed, **model_kwargs)
    model.fit(x_train, y_train)

    pred_test = model.predict(x_test)
    rmse = mean_squared_error(y_test, pred_test)
    r2 = r2_score(y_test, pred_test)
    mae = mean_absolute_error(y_test, pred_test)
    
    del model

    return [rmse, r2, mae]


MLP_model_kwargs = {'hidden_layer_sizes': HIDDEN_LAYER_SIZES,
                  'activation': ACTIVATION,
                  'solver': SOLVER,
                  'early_stopping': True,
                  'validation_fraction': VALIDATION_TRAIN_RATIO,
                  'n_iter_no_change': N_ITER_NO_CHANGE,
                  'learning_rate_init': 0.001,
                  'learning_rate': 'adaptive',
                  'max_iter': MAX_ITER,
                  'tol': TOL}

KAN_model_kwargs = {'hidden_layer_sizes': [1,],
                    'grid': 3,
                    'k': 3,
                    'solver': 'lbfgs',
                    'max_iter': 100,
                    'lamb': 1e-2,
                    'lamb_l1': 1,
                    'lamb_entropy': 2,
                    'n_iter_no_change': 30,
                    'tol': 1e-3
                    }

lmdKAN_model_kwargs = {'hidden_layer_sizes': [5,2],
                       'grid': 3,
                       'k': 3,
                       'solver': 'lbfgs',
                       'max_iter': 100,
                       'lamb': 1e-2,
                       'lamb_l1': 1,
                       'lamb_entropy': 2,
                       'n_iter_no_change': 30,
                       'tol': 1e-3
                       }

In [4]:
def multi_exp(l_algos_names,
              l_algos,
              mult_X_Y,
              l_kwargs,
              l_metrics_names,
              num_iter):
    ''' Function, that process algos(X, Y) and returns df of their metrics. 
    '''
    res_list = []

    for alg, (x, y), kwargs, alg_name in zip(l_algos, mult_X_Y, l_kwargs, l_algos_names):
        print(f'--- Processing {alg_name}')

        for i in range(1, num_iter+1):
            print(f'iter: {i}')
            #print(kwargs)
            l_metrics = alg(x, y, seed=i, **kwargs)
            res_list.append([alg_name, i]+l_metrics)
        print('-------')

    return pd.DataFrame(res_list, columns=['alg_name', 'iter']+l_metrics_names)

In [5]:
l_algos_names=['MLP_Cr', 'MLP_Cu', 'MLP_Ni', 'MLP_NO3',
               'KAN_Cr', 'KAN_Cu', 'KAN_Ni', 'KAN_NO3',
               'lmdKAN_Cr', 'lmdKAN_Cu', 'lmdKAN_Ni', 'lmdKAN_NO3']

l_algos=[alg_sklMLP_model, alg_sklMLP_model, alg_sklMLP_model, alg_sklMLP_model,
         alg_sklKAN_model, alg_sklKAN_model, alg_sklKAN_model, alg_sklKAN_model,
         alg_sklKAN_model, alg_sklKAN_model, alg_sklKAN_model, alg_sklKAN_model]

mult_X_Y=[(x, y_Cr), (x, y_Cu), (x, y_Ni), (x, y_NO3), 
          (x, y_Cr), (x, y_Cu), (x, y_Ni), (x, y_NO3),
          (x, y_Cr), (x, y_Cu), (x, y_Ni), (x, y_NO3)]

l_kwargs=[{'class_model': MLPRegressor,'model_kwargs': MLP_model_kwargs},
          {'class_model': MLPRegressor,'model_kwargs': MLP_model_kwargs},
          {'class_model': MLPRegressor,'model_kwargs': MLP_model_kwargs},
          {'class_model': MLPRegressor,'model_kwargs': MLP_model_kwargs},
          
          {'class_model': KANRegressor,'model_kwargs': KAN_model_kwargs},
          {'class_model': KANRegressor,'model_kwargs': KAN_model_kwargs},
          {'class_model': KANRegressor,'model_kwargs': KAN_model_kwargs},
          {'class_model': KANRegressor,'model_kwargs': KAN_model_kwargs},
          
          {'class_model': lmdKANRegressor,'model_kwargs': lmdKAN_model_kwargs},
          {'class_model': lmdKANRegressor,'model_kwargs': lmdKAN_model_kwargs},
          {'class_model': lmdKANRegressor,'model_kwargs': lmdKAN_model_kwargs},
          {'class_model': lmdKANRegressor,'model_kwargs': lmdKAN_model_kwargs},]

l_metrics_names=['rmse', 'r2', 'mae']

num_iter=100

In [6]:
full_df = multi_exp(l_algos_names=l_algos_names,
                    l_algos=l_algos,
                    mult_X_Y=mult_X_Y,
                    l_kwargs=l_kwargs,
                    l_metrics_names=l_metrics_names,
                    num_iter=num_iter)

--- Processing MLP_Cr
iter: 1
iter: 2
iter: 3
iter: 4
iter: 5
iter: 6
iter: 7
iter: 8
iter: 9
iter: 10
iter: 11
iter: 12
iter: 13
iter: 14
iter: 15
iter: 16
iter: 17
iter: 18
iter: 19
iter: 20
iter: 21
iter: 22
iter: 23
iter: 24
iter: 25
iter: 26
iter: 27
iter: 28
iter: 29
iter: 30
iter: 31
iter: 32
iter: 33
iter: 34
iter: 35
iter: 36
iter: 37
iter: 38
iter: 39
iter: 40
iter: 41
iter: 42
iter: 43
iter: 44
iter: 45
iter: 46
iter: 47
iter: 48
iter: 49
iter: 50
iter: 51
iter: 52
iter: 53
iter: 54
iter: 55
iter: 56
iter: 57
iter: 58
iter: 59
iter: 60
iter: 61
iter: 62
iter: 63
iter: 64
iter: 65
iter: 66
iter: 67
iter: 68
iter: 69
iter: 70
iter: 71
iter: 72
iter: 73
iter: 74
iter: 75
iter: 76
iter: 77
iter: 78
iter: 79
iter: 80
iter: 81
iter: 82
iter: 83
iter: 84
iter: 85
iter: 86
iter: 87
iter: 88
iter: 89
iter: 90
iter: 91
iter: 92
iter: 93
iter: 94
iter: 95
iter: 96
iter: 97
iter: 98
iter: 99
iter: 100
-------
--- Processing MLP_Cu
iter: 1
iter: 2
iter: 3
iter: 4
iter: 5
iter: 6
iter: 7
iter: 8
iter: 9
iter: 10
iter: 11
iter: 12
iter: 13
iter: 14
iter: 15
iter: 16
iter: 17
iter: 18
iter: 19
iter: 20
iter: 21
iter: 22
iter: 23
iter: 24
iter: 25
iter: 26
iter: 27
iter: 28
iter: 29
iter: 30
iter: 31
iter: 32
iter: 33
iter: 34
iter: 35
iter: 36
iter: 37
iter: 38
iter: 39
iter: 40
iter: 41
iter: 42
iter: 43
iter: 44
iter: 45
iter: 46
iter: 47
iter: 48
iter: 49
iter: 50
iter: 51
iter: 52
iter: 53
iter: 54
iter: 55
iter: 56
iter: 57
iter: 58
iter: 59
iter: 60
iter: 61
iter: 62
iter: 63
iter: 64
iter: 65
iter: 66
iter: 67
iter: 68
iter: 69
iter: 70
iter: 71
iter: 72
iter: 73
iter: 74
iter: 75
iter: 76
iter: 77
iter: 78
iter: 79
iter: 80
iter: 81
iter: 82
iter: 83
iter: 84
iter: 85
iter: 86
iter: 87
iter: 88
iter: 89
iter: 90
iter: 91
iter: 92
iter: 93
iter: 94
iter: 95
iter: 96
iter: 97
iter: 98
iter: 99
iter: 100
-------
--- Processing MLP_Ni
iter: 1
iter: 2
iter: 3
iter: 4
iter: 5
iter: 6
iter: 7
iter: 8
iter: 9
iter: 10
iter: 11
iter: 12
iter: 13
iter: 14
iter: 15
iter: 16
iter: 17
iter: 18
iter: 19
iter: 20
iter: 21
iter: 22
iter: 23
iter: 24
iter: 25
iter: 26
iter: 27
iter: 28
iter: 29
iter: 30
iter: 31
iter: 32
iter: 33
iter: 34
iter: 35
iter: 36
iter: 37
iter: 38
iter: 39
iter: 40
iter: 41
iter: 42
iter: 43
iter: 44
iter: 45
iter: 46
iter: 47
iter: 48
iter: 49
iter: 50
iter: 51
iter: 52
iter: 53
iter: 54
iter: 55
iter: 56
iter: 57
iter: 58
iter: 59
iter: 60
iter: 61
iter: 62
iter: 63
iter: 64
iter: 65
iter: 66
iter: 67
iter: 68
iter: 69
iter: 70
iter: 71
iter: 72
iter: 73
iter: 74
iter: 75
iter: 76
iter: 77
iter: 78
iter: 79
iter: 80
iter: 81
iter: 82
iter: 83
iter: 84
iter: 85
iter: 86
iter: 87
iter: 88
iter: 89
iter: 90
iter: 91
iter: 92
iter: 93
iter: 94
iter: 95
iter: 96
iter: 97
iter: 98
iter: 99
iter: 100
-------
--- Processing MLP_NO3
iter: 1
iter: 2
iter: 3
iter: 4
iter: 5
iter: 6
iter: 7
iter: 8
iter: 9
iter: 10
iter: 11
iter: 12
iter: 13
iter: 14
iter: 15
iter: 16
iter: 17
iter: 18
iter: 19
iter: 20
iter: 21
iter: 22
iter: 23
iter: 24
iter: 25
iter: 26
iter: 27
iter: 28
iter: 29
iter: 30
iter: 31
iter: 32
iter: 33
iter: 34
iter: 35
iter: 36
iter: 37
iter: 38
iter: 39
iter: 40
iter: 41
iter: 42
iter: 43
iter: 44
iter: 45
iter: 46
iter: 47
iter: 48
iter: 49
iter: 50
iter: 51
iter: 52
iter: 53
iter: 54
iter: 55
iter: 56
iter: 57
iter: 58
iter: 59
iter: 60
iter: 61
iter: 62
iter: 63
iter: 64
iter: 65
iter: 66
iter: 67
iter: 68
iter: 69
iter: 70
iter: 71
iter: 72
iter: 73
iter: 74
iter: 75
iter: 76
iter: 77
iter: 78
iter: 79
iter: 80
iter: 81
iter: 82
iter: 83
iter: 84
iter: 85
iter: 86
iter: 87
iter: 88
iter: 89
iter: 90
iter: 91
iter: 92
iter: 93
iter: 94
iter: 95
iter: 96
iter: 97
iter: 98
iter: 99
iter: 100
-------
--- Processing KAN_Cr
iter: 1
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.24e-01 | tst_loss: 3.36e-01 | e_stop: 30/30 | reg: 9.37e+00 | :  94%|▉| 94/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 2
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.07e-01 | tst_loss: 3.66e-01 | e_stop: 30/30 | reg: 7.38e+00 | :  36%|▎| 36/100 [00:05<

Early stopping criteria raised
saving model version 0.1
iter: 3
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.25e-01 | tst_loss: 3.05e-01 | e_stop: 30/30 | reg: 9.58e+00 | :  42%|▍| 42/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 4
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.27e-01 | tst_loss: 3.23e-01 | e_stop: 30/30 | reg: 9.43e+00 | :  94%|▉| 94/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 5
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.41e-01 | tst_loss: 2.84e-01 | e_stop: 30/30 | reg: 9.34e+00 | :  87%|▊| 87/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 6
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.30e-01 | tst_loss: 3.19e-01 | e_stop: 30/30 | reg: 9.34e+00 | :  45%|▍| 45/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 7
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.21e-01 | tst_loss: 3.55e-01 | e_stop: 30/30 | reg: 9.56e+00 | :  42%|▍| 42/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 8
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.13e-01 | tst_loss: 3.75e-01 | e_stop: 30/30 | reg: 9.43e+00 | :  38%|▍| 38/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 9
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.24e-01 | tst_loss: 3.25e-01 | e_stop: 30/30 | reg: 9.14e+00 | :  38%|▍| 38/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 10
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.21e-01 | tst_loss: 3.48e-01 | e_stop: 30/30 | reg: 9.45e+00 | :  70%|▋| 70/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 11
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.30e-01 | tst_loss: 2.57e-01 | e_stop: 30/30 | reg: 9.54e+00 | :  71%|▋| 71/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 12
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.24e-01 | tst_loss: 3.53e-01 | e_stop: 30/30 | reg: 9.43e+00 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 13
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 8.97e-01 | tst_loss: 9.66e-01 | e_stop: 30/30 | reg: 8.21e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 14
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.29e-01 | tst_loss: 3.50e-01 | e_stop: 30/30 | reg: 9.62e+00 | :  79%|▊| 79/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 15
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.23e-01 | tst_loss: 3.50e-01 | e_stop: 30/30 | reg: 9.54e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 16
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.32e-01 | tst_loss: 3.17e-01 | e_stop: 30/30 | reg: 9.55e+00 | :  61%|▌| 61/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 17
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.20e-01 | tst_loss: 4.19e-01 | e_stop: 30/30 | reg: 9.02e+00 | :  63%|▋| 63/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 18
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.23e-01 | tst_loss: 3.81e-01 | e_stop: 30/30 | reg: 9.51e+00 | :  44%|▍| 44/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 19
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.38e-01 | tst_loss: 3.39e-01 | e_stop: 30/30 | reg: 9.62e+00 | :  54%|▌| 54/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 20
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.35e-01 | tst_loss: 3.99e-01 | e_stop: 30/30 | reg: 9.31e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 21
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.65e-01 | tst_loss: 3.26e-01 | e_stop: 30/30 | reg: 9.25e+00 | :  38%|▍| 38/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 22
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.26e-01 | tst_loss: 3.86e-01 | e_stop: 30/30 | reg: 9.64e+00 | :  54%|▌| 54/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 23
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.30e-01 | tst_loss: 3.98e-01 | e_stop: 30/30 | reg: 9.11e+00 | :  45%|▍| 45/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 24
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.33e-01 | tst_loss: 3.04e-01 | e_stop: 30/30 | reg: 9.52e+00 | :  93%|▉| 93/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 25
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.37e-01 | tst_loss: 3.13e-01 | e_stop: 30/30 | reg: 9.20e+00 | :  41%|▍| 41/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 26
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.27e-01 | tst_loss: 3.47e-01 | e_stop: 30/30 | reg: 9.56e+00 | :  88%|▉| 88/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 27
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.25e-01 | tst_loss: 3.44e-01 | e_stop: 30/30 | reg: 9.39e+00 | :  43%|▍| 43/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 28
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.99e-01 | tst_loss: 5.51e-01 | e_stop: 30/30 | reg: 7.50e+00 | :  69%|▋| 69/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 29
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.32e-01 | tst_loss: 3.57e-01 | e_stop: 30/30 | reg: 9.05e+00 | :  34%|▎| 34/100 [00:05<

Early stopping criteria raised
saving model version 0.1
iter: 30
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.24e-01 | tst_loss: 3.11e-01 | e_stop: 30/30 | reg: 9.37e+00 | :  47%|▍| 47/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 31
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.39e-01 | tst_loss: 3.32e-01 | e_stop: 30/30 | reg: 9.06e+00 | :  44%|▍| 44/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 32
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.20e-01 | tst_loss: 7.66e-01 | e_stop: 30/30 | reg: 6.97e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 33
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.29e-01 | tst_loss: 3.11e-01 | e_stop: 30/30 | reg: 9.41e+00 | :  56%|▌| 56/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 34
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.17e-01 | tst_loss: 3.66e-01 | e_stop: 8/30 | reg: 9.32e+00 | : 100%|█| 100/100 [00:20<

saving model version 0.1
iter: 35
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.24e-01 | tst_loss: 3.32e-01 | e_stop: 30/30 | reg: 9.49e+00 | :  43%|▍| 43/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 36
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.33e-01 | tst_loss: 2.70e-01 | e_stop: 30/30 | reg: 9.45e+00 | :  74%|▋| 74/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 37
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.33e-01 | tst_loss: 3.21e-01 | e_stop: 30/30 | reg: 9.43e+00 | :  42%|▍| 42/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 38
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.30e-01 | tst_loss: 3.65e-01 | e_stop: 30/30 | reg: 9.55e+00 | :  39%|▍| 39/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 39
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.30e-01 | tst_loss: 3.93e-01 | e_stop: 30/30 | reg: 9.19e+00 | :  46%|▍| 46/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 40
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.51e-01 | tst_loss: 3.60e-01 | e_stop: 30/30 | reg: 9.09e+00 | :  31%|▎| 31/100 [00:04<

Early stopping criteria raised
saving model version 0.1
iter: 41
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.32e-01 | tst_loss: 3.08e-01 | e_stop: 30/30 | reg: 9.30e+00 | :  94%|▉| 94/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 42
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.31e-01 | tst_loss: 3.17e-01 | e_stop: 30/30 | reg: 9.49e+00 | :  58%|▌| 58/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 43
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.28e-01 | tst_loss: 2.98e-01 | e_stop: 30/30 | reg: 9.47e+00 | :  69%|▋| 69/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 44
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.39e-01 | tst_loss: 3.52e-01 | e_stop: 30/30 | reg: 9.11e+00 | :  56%|▌| 56/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 45
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.08e-01 | tst_loss: 3.88e-01 | e_stop: 30/30 | reg: 7.64e+00 | :  50%|▌| 50/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 46
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.37e-01 | tst_loss: 3.13e-01 | e_stop: 30/30 | reg: 9.43e+00 | :  50%|▌| 50/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 47
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.25e-01 | tst_loss: 3.27e-01 | e_stop: 30/30 | reg: 9.49e+00 | :  49%|▍| 49/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 48
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.24e-01 | tst_loss: 3.16e-01 | e_stop: 30/30 | reg: 9.56e+00 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 49
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.22e-01 | tst_loss: 3.47e-01 | e_stop: 24/30 | reg: 9.66e+00 | : 100%|█| 100/100 [00:19

saving model version 0.1
iter: 50
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.06e-01 | tst_loss: 4.42e-01 | e_stop: 30/30 | reg: 7.30e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 51
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.34e-01 | tst_loss: 3.03e-01 | e_stop: 30/30 | reg: 9.53e+00 | :  45%|▍| 45/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 52
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.32e-01 | tst_loss: 3.75e-01 | e_stop: 30/30 | reg: 9.08e+00 | :  43%|▍| 43/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 53
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.26e-01 | tst_loss: 2.93e-01 | e_stop: 30/30 | reg: 9.54e+00 | :  65%|▋| 65/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 54
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.47e-01 | tst_loss: 3.25e-01 | e_stop: 30/30 | reg: 9.07e+00 | :  38%|▍| 38/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 55
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.28e-01 | tst_loss: 3.34e-01 | e_stop: 30/30 | reg: 9.38e+00 | :  42%|▍| 42/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 56
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.23e-01 | tst_loss: 3.75e-01 | e_stop: 30/30 | reg: 9.38e+00 | :  44%|▍| 44/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 57
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.18e-01 | tst_loss: 3.44e-01 | e_stop: 30/30 | reg: 9.61e+00 | :  53%|▌| 53/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 58
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.26e-01 | tst_loss: 3.36e-01 | e_stop: 30/30 | reg: 9.43e+00 | :  48%|▍| 48/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 59
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.15e-01 | tst_loss: 4.87e-01 | e_stop: 30/30 | reg: 7.20e+00 | :  33%|▎| 33/100 [00:03<

Early stopping criteria raised
saving model version 0.1
iter: 60
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.35e-01 | tst_loss: 3.13e-01 | e_stop: 30/30 | reg: 9.54e+00 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 61
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.05e-01 | tst_loss: 4.15e-01 | e_stop: 30/30 | reg: 7.34e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 62
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.12e-01 | tst_loss: 4.12e-01 | e_stop: 30/30 | reg: 9.46e+00 | :  65%|▋| 65/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 63
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.26e-01 | tst_loss: 3.65e-01 | e_stop: 30/30 | reg: 9.50e+00 | :  55%|▌| 55/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 64
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.33e-01 | tst_loss: 3.80e-01 | e_stop: 30/30 | reg: 9.16e+00 | :  40%|▍| 40/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 65
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.50e-01 | tst_loss: 3.58e-01 | e_stop: 30/30 | reg: 9.32e+00 | :  49%|▍| 49/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 66
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.39e-01 | tst_loss: 3.48e-01 | e_stop: 30/30 | reg: 9.33e+00 | :  56%|▌| 56/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 67
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.27e-01 | tst_loss: 3.99e-01 | e_stop: 30/30 | reg: 9.65e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 68
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: nan | tst_loss: nan | e_stop: 0/30 | reg: nan | : 100%|█| 100/100 [00:20<00:00,  4.80it/

saving model version 0.1
iter: 69
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.55e-01 | tst_loss: 3.52e-01 | e_stop: 30/30 | reg: 9.20e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 70
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.26e-01 | tst_loss: 3.45e-01 | e_stop: 30/30 | reg: 9.19e+00 | :  47%|▍| 47/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 71
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.28e-01 | tst_loss: 3.52e-01 | e_stop: 30/30 | reg: 9.31e+00 | :  60%|▌| 60/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 72
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.24e-01 | tst_loss: 3.33e-01 | e_stop: 30/30 | reg: 9.44e+00 | :  45%|▍| 45/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 73
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.34e-01 | tst_loss: 2.72e-01 | e_stop: 30/30 | reg: 9.16e+00 | :  50%|▌| 50/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 74
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 9.23e-01 | tst_loss: 1.13e+00 | e_stop: 30/30 | reg: 7.68e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 75
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.28e-01 | tst_loss: 3.67e-01 | e_stop: 30/30 | reg: 9.48e+00 | :  81%|▊| 81/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 76
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.37e-01 | tst_loss: 4.10e-01 | e_stop: 30/30 | reg: 9.09e+00 | :  46%|▍| 46/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 77
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.27e-01 | tst_loss: 2.99e-01 | e_stop: 30/30 | reg: 9.38e+00 | :  39%|▍| 39/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 78
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.40e-01 | tst_loss: 3.33e-01 | e_stop: 30/30 | reg: 9.17e+00 | :  41%|▍| 41/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 79
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.32e-01 | tst_loss: 3.02e-01 | e_stop: 30/30 | reg: 9.27e+00 | :  48%|▍| 48/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 80
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.18e-01 | tst_loss: 3.67e-01 | e_stop: 30/30 | reg: 9.51e+00 | :  53%|▌| 53/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 81
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.33e-01 | tst_loss: 3.05e-01 | e_stop: 30/30 | reg: 9.67e+00 | :  60%|▌| 60/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 82
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.28e-01 | tst_loss: 3.31e-01 | e_stop: 30/30 | reg: 9.44e+00 | :  45%|▍| 45/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 83
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.38e-01 | tst_loss: 3.00e-01 | e_stop: 30/30 | reg: 9.52e+00 | :  67%|▋| 67/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 84
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.35e-01 | tst_loss: 3.68e-01 | e_stop: 26/30 | reg: 9.54e+00 | : 100%|█| 100/100 [00:19

saving model version 0.1
iter: 85
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.16e-01 | tst_loss: 3.54e-01 | e_stop: 30/30 | reg: 9.34e+00 | :  50%|▌| 50/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 86
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.47e-01 | tst_loss: 2.57e-01 | e_stop: 30/30 | reg: 9.11e+00 | :  49%|▍| 49/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 87
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.29e-01 | tst_loss: 3.74e-01 | e_stop: 30/30 | reg: 9.65e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 88
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.25e-01 | tst_loss: 3.30e-01 | e_stop: 30/30 | reg: 9.45e+00 | :  56%|▌| 56/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 89
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.92e-01 | tst_loss: 4.46e-01 | e_stop: 30/30 | reg: 9.55e+00 | :  65%|▋| 65/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 90
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.35e-01 | tst_loss: 3.82e-01 | e_stop: 30/30 | reg: 9.18e+00 | :  46%|▍| 46/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 91
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.37e-01 | tst_loss: 3.72e-01 | e_stop: 30/30 | reg: 9.02e+00 | :  36%|▎| 36/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 92
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.32e-01 | tst_loss: 2.86e-01 | e_stop: 30/30 | reg: 9.52e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 93
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.32e-01 | tst_loss: 4.25e-01 | e_stop: 30/30 | reg: 9.21e+00 | :  34%|▎| 34/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 94
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.37e-01 | tst_loss: 3.68e-01 | e_stop: 30/30 | reg: 9.06e+00 | :  41%|▍| 41/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 95
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.24e-01 | tst_loss: 3.42e-01 | e_stop: 30/30 | reg: 9.49e+00 | :  63%|▋| 63/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 96
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.33e-01 | tst_loss: 3.82e-01 | e_stop: 30/30 | reg: 9.36e+00 | :  42%|▍| 42/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 97
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.30e-01 | tst_loss: 3.62e-01 | e_stop: 30/30 | reg: 9.46e+00 | :  42%|▍| 42/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 98
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.35e-01 | tst_loss: 3.67e-01 | e_stop: 30/30 | reg: 9.07e+00 | :  59%|▌| 59/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 99
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.33e-01 | tst_loss: 3.68e-01 | e_stop: 30/30 | reg: 9.49e+00 | :  32%|▎| 32/100 [00:05<

Early stopping criteria raised
saving model version 0.1
iter: 100
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.39e-01 | tst_loss: 3.96e-01 | e_stop: 30/30 | reg: 9.45e+00 | :  35%|▎| 35/100 [00:05<

Early stopping criteria raised
saving model version 0.1
-------
--- Processing KAN_Cu
iter: 1
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.16e-01 | tst_loss: 7.84e-01 | e_stop: 30/30 | reg: 8.46e+00 | :  36%|▎| 36/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 2
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.35e-01 | tst_loss: 7.29e-01 | e_stop: 30/30 | reg: 8.45e+00 | :  40%|▍| 40/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 3
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.16e-01 | tst_loss: 7.11e-01 | e_stop: 30/30 | reg: 8.51e+00 | :  39%|▍| 39/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 4
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.12e-01 | tst_loss: 6.41e-01 | e_stop: 30/30 | reg: 9.94e+00 | :  70%|▋| 70/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 5
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.12e-01 | tst_loss: 6.95e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  45%|▍| 45/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 6
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.11e-01 | tst_loss: 7.42e-01 | e_stop: 30/30 | reg: 1.00e+01 | :  56%|▌| 56/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 7
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.90e-01 | tst_loss: 8.29e-01 | e_stop: 30/30 | reg: 9.69e+00 | :  43%|▍| 43/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 8
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.01e-01 | tst_loss: 8.04e-01 | e_stop: 30/30 | reg: 9.92e+00 | :  84%|▊| 84/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 9
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.02e-01 | tst_loss: 7.73e-01 | e_stop: 30/30 | reg: 9.99e+00 | :  40%|▍| 40/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 10
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.94e-01 | tst_loss: 8.11e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  31%|▎| 31/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 11
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.31e-01 | tst_loss: 6.76e-01 | e_stop: 30/30 | reg: 9.91e+00 | :  31%|▎| 31/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 12
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.38e-01 | tst_loss: 7.49e-01 | e_stop: 30/30 | reg: 8.48e+00 | :  31%|▎| 31/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 13
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.18e-01 | tst_loss: 7.27e-01 | e_stop: 30/30 | reg: 8.31e+00 | :  31%|▎| 31/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 14
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.91e-01 | tst_loss: 8.23e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  67%|▋| 67/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 15
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.10e-01 | tst_loss: 7.29e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  51%|▌| 51/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 16
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.27e-01 | tst_loss: 6.87e-01 | e_stop: 30/30 | reg: 9.86e+00 | :  33%|▎| 33/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 17
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.03e-01 | tst_loss: 8.42e-01 | e_stop: 30/30 | reg: 8.39e+00 | :  34%|▎| 34/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 18
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.00e+00 | tst_loss: 1.12e+00 | e_stop: 30/30 | reg: 6.97e+00 | :  59%|▌| 59/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 19
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.11e-01 | tst_loss: 7.10e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  31%|▎| 31/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 20
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.00e+00 | tst_loss: 1.07e+00 | e_stop: 30/30 | reg: 6.84e+00 | :  35%|▎| 35/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 21
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.30e-01 | tst_loss: 7.84e-01 | e_stop: 30/30 | reg: 8.62e+00 | :  40%|▍| 40/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 22
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.26e-01 | tst_loss: 7.16e-01 | e_stop: 30/30 | reg: 9.92e+00 | :  34%|▎| 34/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 23
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.15e-01 | tst_loss: 8.13e-01 | e_stop: 30/30 | reg: 8.39e+00 | :  31%|▎| 31/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 24
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.21e-01 | tst_loss: 6.62e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  71%|▋| 71/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 25
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.16e+00 | tst_loss: 1.19e+00 | e_stop: 30/30 | reg: 8.48e+00 | :  34%|▎| 34/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 26
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.25e-01 | tst_loss: 6.58e-01 | e_stop: 30/30 | reg: 9.94e+00 | :  96%|▉| 96/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 27
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.12e-01 | tst_loss: 7.14e-01 | e_stop: 30/30 | reg: 9.64e+00 | :  32%|▎| 32/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 28
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.39e-01 | tst_loss: 7.06e-01 | e_stop: 30/30 | reg: 8.32e+00 | :  32%|▎| 32/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 29
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.10e-01 | tst_loss: 7.61e-01 | e_stop: 30/30 | reg: 9.93e+00 | :  54%|▌| 54/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 30
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.00e-01 | tst_loss: 7.39e-01 | e_stop: 30/30 | reg: 1.00e+01 | :  60%|▌| 60/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 31
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.28e-01 | tst_loss: 7.06e-01 | e_stop: 30/30 | reg: 8.59e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 32
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.08e-01 | tst_loss: 7.46e-01 | e_stop: 30/30 | reg: 9.43e+00 | :  34%|▎| 34/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 33
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 7.54e-01 | e_stop: 30/30 | reg: 8.51e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 34
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.05e-01 | tst_loss: 7.99e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  35%|▎| 35/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 35
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.99e-01 | tst_loss: 7.42e-01 | e_stop: 30/30 | reg: 1.00e+01 | :  33%|▎| 33/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 36
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.36e-01 | tst_loss: 7.51e-01 | e_stop: 30/30 | reg: 8.40e+00 | :  50%|▌| 50/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 37
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.13e-01 | tst_loss: 7.02e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  61%|▌| 61/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 38
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.98e-01 | tst_loss: 8.20e-01 | e_stop: 30/30 | reg: 9.97e+00 | :  61%|▌| 61/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 39
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.14e-01 | tst_loss: 7.86e-01 | e_stop: 30/30 | reg: 8.50e+00 | :  35%|▎| 35/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 40
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.19e-01 | tst_loss: 6.46e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  42%|▍| 42/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 41
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.09e-01 | tst_loss: 7.03e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  52%|▌| 52/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 42
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.09e-01 | tst_loss: 7.51e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  38%|▍| 38/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 43
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.14e-01 | tst_loss: 6.86e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  35%|▎| 35/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 44
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.15e-01 | tst_loss: 7.85e-01 | e_stop: 30/30 | reg: 9.98e+00 | :  31%|▎| 31/100 [00:05<

Early stopping criteria raised
saving model version 0.1
iter: 45
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.26e-01 | tst_loss: 7.76e-01 | e_stop: 30/30 | reg: 8.66e+00 | :  42%|▍| 42/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 46
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.26e-01 | tst_loss: 7.22e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  62%|▌| 62/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 47
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.04e-01 | tst_loss: 7.16e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  51%|▌| 51/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 48
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.01e+00 | tst_loss: 1.06e+00 | e_stop: 30/30 | reg: 7.34e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 49
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.98e-01 | tst_loss: 8.37e-01 | e_stop: 30/30 | reg: 1.00e+01 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 50
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.30e-01 | tst_loss: 7.02e-01 | e_stop: 30/30 | reg: 8.69e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 51
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.27e-01 | tst_loss: 7.53e-01 | e_stop: 30/30 | reg: 8.35e+00 | :  36%|▎| 36/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 52
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.25e-01 | tst_loss: 7.77e-01 | e_stop: 30/30 | reg: 8.59e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 53
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.11e-01 | tst_loss: 7.13e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 54
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.10e-01 | tst_loss: 7.34e-01 | e_stop: 30/30 | reg: 1.00e+01 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 55
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.00e-01 | tst_loss: 6.58e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 56
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.06e-01 | tst_loss: 6.77e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  52%|▌| 52/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 57
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.22e-01 | tst_loss: 7.21e-01 | e_stop: 30/30 | reg: 8.60e+00 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 58
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.07e-01 | tst_loss: 7.27e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 59
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.09e-01 | tst_loss: 8.75e-01 | e_stop: 30/30 | reg: 8.39e+00 | :  35%|▎| 35/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 60
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.50e-01 | tst_loss: 6.71e-01 | e_stop: 30/30 | reg: 8.44e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 61
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.29e-01 | tst_loss: 6.80e-01 | e_stop: 30/30 | reg: 8.38e+00 | :  56%|▌| 56/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 62
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.27e-01 | tst_loss: 7.29e-01 | e_stop: 30/30 | reg: 8.50e+00 | :  33%|▎| 33/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 63
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 7.92e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 64
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.35e-01 | tst_loss: 7.32e-01 | e_stop: 30/30 | reg: 8.44e+00 | :  37%|▎| 37/100 [00:04<

Early stopping criteria raised
saving model version 0.1
iter: 65
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.15e-01 | tst_loss: 7.92e-01 | e_stop: 30/30 | reg: 9.82e+00 | :  56%|▌| 56/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 66
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.35e-01 | tst_loss: 6.59e-01 | e_stop: 30/30 | reg: 8.38e+00 | :  36%|▎| 36/100 [00:04<

Early stopping criteria raised
saving model version 0.1
iter: 67
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 8.56e-01 | e_stop: 30/30 | reg: 8.56e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 68
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.08e-01 | tst_loss: 7.09e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  33%|▎| 33/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 69
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 6.82e-01 | e_stop: 30/30 | reg: 8.42e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 70
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.29e-01 | tst_loss: 7.40e-01 | e_stop: 30/30 | reg: 8.69e+00 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 71
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 7.15e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  54%|▌| 54/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 72
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.16e-01 | tst_loss: 6.80e-01 | e_stop: 30/30 | reg: 9.96e+00 | :  55%|▌| 55/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 73
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.22e-01 | tst_loss: 7.50e-01 | e_stop: 30/30 | reg: 8.23e+00 | :  31%|▎| 31/100 [00:04<

Early stopping criteria raised
saving model version 0.1
iter: 74
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.24e-01 | tst_loss: 7.41e-01 | e_stop: 30/30 | reg: 9.91e+00 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 75
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.01e+00 | tst_loss: 1.07e+00 | e_stop: 30/30 | reg: 8.01e+00 | :  34%|▎| 34/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 76
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.96e-01 | tst_loss: 8.92e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  68%|▋| 68/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 77
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.97e-01 | tst_loss: 7.16e-01 | e_stop: 30/30 | reg: 9.97e+00 | :  86%|▊| 86/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 78
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.23e-01 | tst_loss: 7.23e-01 | e_stop: 30/30 | reg: 8.52e+00 | :  55%|▌| 55/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 79
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.06e-01 | tst_loss: 7.23e-01 | e_stop: 30/30 | reg: 1.03e+01 | :  36%|▎| 36/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 80
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.15e-01 | tst_loss: 8.09e-01 | e_stop: 30/30 | reg: 8.45e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 81
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.32e-01 | tst_loss: 5.75e-01 | e_stop: 30/30 | reg: 8.65e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 82
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.07e-01 | tst_loss: 7.43e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  37%|▎| 37/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 83
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.33e-01 | tst_loss: 7.89e-01 | e_stop: 30/30 | reg: 8.40e+00 | :  46%|▍| 46/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 84
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.34e-01 | tst_loss: 7.20e-01 | e_stop: 30/30 | reg: 8.46e+00 | :  40%|▍| 40/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 85
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.29e-01 | tst_loss: 7.46e-01 | e_stop: 30/30 | reg: 8.43e+00 | :  33%|▎| 33/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 86
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.33e-01 | tst_loss: 7.01e-01 | e_stop: 30/30 | reg: 8.66e+00 | :  67%|▋| 67/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 87
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.05e-01 | tst_loss: 8.22e-01 | e_stop: 30/30 | reg: 8.38e+00 | :  36%|▎| 36/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 88
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.20e-01 | tst_loss: 7.02e-01 | e_stop: 30/30 | reg: 9.85e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 89
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.05e+00 | tst_loss: 1.15e+00 | e_stop: 30/30 | reg: 9.18e+00 | :  48%|▍| 48/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 90
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.32e-01 | tst_loss: 6.90e-01 | e_stop: 30/30 | reg: 8.45e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 91
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.20e-01 | tst_loss: 7.24e-01 | e_stop: 30/30 | reg: 8.32e+00 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 92
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.37e-01 | tst_loss: 6.54e-01 | e_stop: 30/30 | reg: 8.60e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 93
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.22e-01 | tst_loss: 7.56e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  39%|▍| 39/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 94
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.37e-01 | tst_loss: 6.79e-01 | e_stop: 30/30 | reg: 8.54e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 95
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.16e-01 | tst_loss: 7.07e-01 | e_stop: 30/30 | reg: 9.94e+00 | :  46%|▍| 46/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 96
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.14e-01 | tst_loss: 7.28e-01 | e_stop: 30/30 | reg: 9.98e+00 | :  45%|▍| 45/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 97
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.12e-01 | tst_loss: 8.81e-01 | e_stop: 30/30 | reg: 8.54e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 98
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.29e-01 | tst_loss: 6.54e-01 | e_stop: 30/30 | reg: 8.38e+00 | :  44%|▍| 44/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 99
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.07e-01 | tst_loss: 7.70e-01 | e_stop: 30/30 | reg: 8.53e+00 | :  43%|▍| 43/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 100
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.06e-01 | tst_loss: 8.79e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  51%|▌| 51/100 [00:10<

Early stopping criteria raised
saving model version 0.1
-------
--- Processing KAN_Ni
iter: 1
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 9.80e+00 | :  38%|▍| 38/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 2
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 6.88e+00 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 3
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 6.49e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 4
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 7.97e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 5
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 8.38e+00 | :  38%|▍| 38/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 6
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.54e+00 | e_stop: 30/30 | reg: 7.59e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 7
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 6.84e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 8
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 7.10e+00 | :  62%|▌| 62/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 9
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 7.62e+00 | :  38%|▍| 38/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 10
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 7.75e+00 | :  39%|▍| 39/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 11
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 7.32e+00 | :  33%|▎| 33/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 12
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.58e+00 | tst_loss: 1.54e+00 | e_stop: 30/30 | reg: 5.47e-01 | :  30%|▎| 30/100 [00:04<

Early stopping criteria raised
saving model version 0.1
iter: 13
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.64e+00 | e_stop: 30/30 | reg: 6.54e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 14
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.61e+00 | e_stop: 30/30 | reg: 8.46e+00 | :  36%|▎| 36/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 15
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 6.66e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 16
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.64e+00 | e_stop: 30/30 | reg: 7.76e+00 | :  47%|▍| 47/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 17
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.49e+00 | e_stop: 30/30 | reg: 7.32e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 18
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 7.98e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 19
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 8.12e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 20
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 6.70e+00 | :  36%|▎| 36/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 21
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.58e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 3.71e-01 | :  31%|▎| 31/100 [00:03<

Early stopping criteria raised
saving model version 0.1
iter: 22
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 6.18e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 23
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 7.25e+00 | :  54%|▌| 54/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 24
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.45e+00 | e_stop: 30/30 | reg: 6.47e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 25
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 7.15e+00 | :  52%|▌| 52/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 26
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 6.54e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 27
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.39e+00 | e_stop: 30/30 | reg: 6.29e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 28
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.70e+00 | e_stop: 30/30 | reg: 6.88e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 29
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.62e+00 | e_stop: 30/30 | reg: 6.81e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 30
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.49e+00 | e_stop: 30/30 | reg: 6.35e+00 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 31
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 6.72e+00 | :  58%|▌| 58/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 32
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.67e+00 | e_stop: 30/30 | reg: 6.06e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 33
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 7.81e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 34
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.50e+00 | e_stop: 30/30 | reg: 6.56e+00 | :  46%|▍| 46/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 35
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.47e+00 | e_stop: 30/30 | reg: 8.54e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 36
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 8.83e+00 | :  98%|▉| 98/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 37
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.61e+00 | e_stop: 30/30 | reg: 6.03e+00 | :  39%|▍| 39/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 38
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.64e+00 | e_stop: 30/30 | reg: 7.71e+00 | :  31%|▎| 31/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 39
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.49e+00 | e_stop: 30/30 | reg: 6.06e+00 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 40
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 8.54e+00 | :  51%|▌| 51/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 41
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 7.62e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 42
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.47e+00 | e_stop: 30/30 | reg: 6.22e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 43
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 7.59e+00 | :  45%|▍| 45/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 44
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.45e+00 | e_stop: 30/30 | reg: 6.32e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 45
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.67e+00 | e_stop: 30/30 | reg: 8.51e+00 | :  40%|▍| 40/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 46
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.70e+00 | e_stop: 30/30 | reg: 9.31e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 47
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 6.78e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 48
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.57e+00 | e_stop: 30/30 | reg: 6.80e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 49
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 7.04e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 50
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.53e+00 | e_stop: 30/30 | reg: 6.28e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 51
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 8.42e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 52
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.53e+00 | e_stop: 30/30 | reg: 7.48e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 53
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.54e+00 | e_stop: 30/30 | reg: 8.25e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 54
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.61e+00 | e_stop: 30/30 | reg: 7.17e+00 | :  32%|▎| 32/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 55
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 2.16e+00 | e_stop: 30/30 | reg: 8.82e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 56
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.49e+00 | e_stop: 30/30 | reg: 7.04e+00 | :  34%|▎| 34/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 57
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 7.34e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 58
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.62e+00 | e_stop: 30/30 | reg: 7.50e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 59
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.54e+00 | e_stop: 30/30 | reg: 8.26e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 60
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 6.16e+00 | :  87%|▊| 87/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 61
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.43e+00 | e_stop: 30/30 | reg: 8.69e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 62
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 7.64e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 63
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.42e+00 | e_stop: 30/30 | reg: 7.34e+00 | :  32%|▎| 32/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 64
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.69e+00 | e_stop: 30/30 | reg: 8.96e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 65
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 6.45e+00 | :  50%|▌| 50/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 66
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 7.62e+00 | :  36%|▎| 36/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 67
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 6.90e+00 | :  39%|▍| 39/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 68
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.66e+00 | e_stop: 30/30 | reg: 7.02e+00 | :  59%|▌| 59/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 69
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.66e+00 | e_stop: 30/30 | reg: 6.35e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 70
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.56e+00 | tst_loss: 1.78e+00 | e_stop: 30/30 | reg: 3.96e-01 | :  31%|▎| 31/100 [00:03<

Early stopping criteria raised
saving model version 0.1
iter: 71
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 7.76e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 72
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.52e+00 | tst_loss: 1.38e+00 | e_stop: 30/30 | reg: 6.27e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 73
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 2.66e+00 | e_stop: 30/30 | reg: 7.77e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 74
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.43e+00 | e_stop: 30/30 | reg: 6.42e+00 | :  83%|▊| 83/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 75
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.60e+00 | tst_loss: 1.54e+00 | e_stop: 30/30 | reg: 4.04e-01 | :  30%|▎| 30/100 [00:04<

Early stopping criteria raised
saving model version 0.1
iter: 76
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 7.26e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 77
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.66e+00 | e_stop: 30/30 | reg: 7.49e+00 | :  36%|▎| 36/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 78
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.42e+00 | e_stop: 30/30 | reg: 6.41e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 79
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 6.88e+00 | :  36%|▎| 36/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 80
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.60e+00 | tst_loss: 1.45e+00 | e_stop: 30/30 | reg: 6.51e-01 | :  31%|▎| 31/100 [00:04<

Early stopping criteria raised
saving model version 0.1
iter: 81
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.57e+00 | e_stop: 30/30 | reg: 7.77e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 82
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.55e+00 | e_stop: 30/30 | reg: 7.49e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 83
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.41e+00 | e_stop: 30/30 | reg: 7.83e+00 | :  36%|▎| 36/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 84
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.57e+00 | e_stop: 30/30 | reg: 8.32e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 85
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.55e+00 | e_stop: 30/30 | reg: 6.20e+00 | :  47%|▍| 47/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 86
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.53e+00 | tst_loss: 1.47e+00 | e_stop: 30/30 | reg: 9.57e+00 | :  40%|▍| 40/100 [00:05<

Early stopping criteria raised
saving model version 0.1
iter: 87
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 7.63e+00 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 88
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.72e+00 | e_stop: 30/30 | reg: 8.39e+00 | :  36%|▎| 36/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 89
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.99e+00 | e_stop: 30/30 | reg: 7.92e+00 | :  53%|▌| 53/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 90
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.46e+00 | e_stop: 30/30 | reg: 9.23e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 91
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.68e+00 | e_stop: 30/30 | reg: 6.72e+00 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 92
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.57e+00 | tst_loss: 1.44e+00 | e_stop: 30/30 | reg: 5.50e-01 | :  30%|▎| 30/100 [00:04<

Early stopping criteria raised
saving model version 0.1
iter: 93
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.68e+00 | e_stop: 30/30 | reg: 8.34e+00 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 94
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 8.63e+00 | :  44%|▍| 44/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 95
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.43e+00 | e_stop: 30/30 | reg: 7.77e+00 | :  37%|▎| 37/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 96
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.53e+00 | e_stop: 30/30 | reg: 7.15e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 97
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.53e+00 | e_stop: 30/30 | reg: 7.49e+00 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 98
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 7.25e+00 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 99
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 7.13e+00 | :  64%|▋| 64/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 100
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 7.45e+00 | :  75%|▊| 75/100 [00:15<

Early stopping criteria raised
saving model version 0.1
-------
--- Processing KAN_NO3
iter: 1
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 2.99e+00 | e_stop: 30/30 | reg: 1.41e+01 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 2
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.08e+00 | e_stop: 30/30 | reg: 1.43e+01 | :  63%|▋| 63/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 3
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.00e+00 | e_stop: 30/30 | reg: 1.73e+01 | :  48%|▍| 48/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 4
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 3.17e+00 | e_stop: 30/30 | reg: 2.08e+01 | :  45%|▍| 45/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 5
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.98e+00 | e_stop: 29/30 | reg: 1.63e+01 | : 100%|█| 100/100 [00:24

saving model version 0.1
iter: 6
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 2.90e+00 | e_stop: 30/30 | reg: 1.98e+01 | :  38%|▍| 38/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 7
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.86e+00 | tst_loss: 2.90e+00 | e_stop: 30/30 | reg: 1.52e+01 | :  91%|▉| 91/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 8
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 2.46e+01 | :  30%|▎| 30/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 9
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.83e+00 | e_stop: 30/30 | reg: 1.37e+01 | :  39%|▍| 39/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 10
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 2.96e+00 | e_stop: 30/30 | reg: 1.45e+01 | :  70%|▋| 70/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 11
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 2.95e+00 | e_stop: 30/30 | reg: 1.41e+01 | :  31%|▎| 31/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 12
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.94e+00 | tst_loss: 2.73e+00 | e_stop: 30/30 | reg: 1.89e+01 | :  48%|▍| 48/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 13
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.28e+00 | e_stop: 30/30 | reg: 1.37e+01 | :  45%|▍| 45/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 14
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 3.11e+00 | e_stop: 30/30 | reg: 1.79e+01 | :  35%|▎| 35/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 15
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.11e+00 | e_stop: 30/30 | reg: 1.76e+01 | :  35%|▎| 35/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 16
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  67%|▋| 67/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 17
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.97e+00 | tst_loss: 3.01e+00 | e_stop: 30/30 | reg: 1.61e+01 | :  69%|▋| 69/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 18
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.00e+00 | e_stop: 30/30 | reg: 1.42e+01 | :  50%|▌| 50/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 19
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.18e+00 | e_stop: 30/30 | reg: 2.26e+01 | :  56%|▌| 56/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 20
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 2.93e+00 | e_stop: 30/30 | reg: 1.38e+01 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 21
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 1.45e+01 | :  46%|▍| 46/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 22
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.93e+00 | e_stop: 30/30 | reg: 1.86e+01 | :  51%|▌| 51/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 23
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.84e+00 | tst_loss: 3.23e+00 | e_stop: 30/30 | reg: 1.50e+01 | :  75%|▊| 75/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 24
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.71e+00 | e_stop: 30/30 | reg: 1.89e+01 | :  72%|▋| 72/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 25
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.86e+00 | tst_loss: 3.07e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  42%|▍| 42/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 26
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.14e+00 | e_stop: 30/30 | reg: 1.87e+01 | :  45%|▍| 45/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 27
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 2.81e+00 | e_stop: 30/30 | reg: 1.68e+01 | :  78%|▊| 78/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 28
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.20e+00 | e_stop: 30/30 | reg: 1.35e+01 | :  62%|▌| 62/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 29
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.81e+00 | tst_loss: 3.21e+00 | e_stop: 30/30 | reg: 1.85e+01 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 30
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.11e+00 | e_stop: 30/30 | reg: 1.63e+01 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 31
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.16e+00 | e_stop: 30/30 | reg: 1.37e+01 | :  85%|▊| 85/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 32
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.15e+00 | e_stop: 30/30 | reg: 2.42e+01 | :  43%|▍| 43/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 33
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.84e+00 | tst_loss: 3.28e+00 | e_stop: 30/30 | reg: 1.37e+01 | :  35%|▎| 35/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 34
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 2.78e+00 | e_stop: 30/30 | reg: 1.39e+01 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 35
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 2.98e+00 | e_stop: 30/30 | reg: 1.62e+01 | :  38%|▍| 38/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 36
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.77e+00 | e_stop: 30/30 | reg: 1.44e+01 | :  47%|▍| 47/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 37
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.11e+00 | e_stop: 30/30 | reg: 1.88e+01 | :  80%|▊| 80/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 38
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.19e+00 | e_stop: 30/30 | reg: 2.07e+01 | :  46%|▍| 46/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 39
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.86e+00 | tst_loss: 3.06e+00 | e_stop: 30/30 | reg: 1.42e+01 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 40
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.94e+00 | e_stop: 30/30 | reg: 1.38e+01 | :  40%|▍| 40/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 41
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 2.97e+00 | e_stop: 30/30 | reg: 1.56e+01 | :  97%|▉| 97/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 42
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.00e+00 | e_stop: 30/30 | reg: 2.50e+01 | :  80%|▊| 80/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 43
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.03e+00 | e_stop: 30/30 | reg: 1.51e+01 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 44
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 2.80e+00 | e_stop: 30/30 | reg: 1.69e+01 | :  34%|▎| 34/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 45
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 3.16e+00 | e_stop: 30/30 | reg: 1.43e+01 | :  44%|▍| 44/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 46
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.96e+00 | e_stop: 30/30 | reg: 1.38e+01 | :  59%|▌| 59/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 47
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.04e+00 | e_stop: 20/30 | reg: 2.32e+01 | : 100%|█| 100/100 [00:20

saving model version 0.1
iter: 48
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.86e+00 | e_stop: 30/30 | reg: 1.39e+01 | :  71%|▋| 71/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 49
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.10e+00 | e_stop: 30/30 | reg: 1.77e+01 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 50
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.94e+00 | tst_loss: 2.99e+00 | e_stop: 30/30 | reg: 1.74e+01 | :  48%|▍| 48/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 51
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.78e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  75%|▊| 75/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 52
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.71e+00 | e_stop: 30/30 | reg: 2.06e+01 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 53
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.94e+00 | e_stop: 30/30 | reg: 2.10e+01 | :  74%|▋| 74/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 54
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 2.85e+00 | e_stop: 30/30 | reg: 2.04e+01 | :  51%|▌| 51/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 55
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.25e+00 | e_stop: 30/30 | reg: 1.55e+01 | :  39%|▍| 39/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 56
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.99e+00 | tst_loss: 2.86e+00 | e_stop: 30/30 | reg: 1.17e+01 | :  47%|▍| 47/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 57
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.89e+00 | e_stop: 30/30 | reg: 1.37e+01 | :  36%|▎| 36/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 58
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 2.93e+00 | e_stop: 30/30 | reg: 2.00e+01 | :  85%|▊| 85/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 59
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 3.01e+00 | e_stop: 30/30 | reg: 1.38e+01 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 60
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.86e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  58%|▌| 58/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 61
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 2.80e+00 | e_stop: 30/30 | reg: 1.52e+01 | :  43%|▍| 43/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 62
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.03e+00 | e_stop: 30/30 | reg: 1.49e+01 | :  47%|▍| 47/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 63
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.76e+00 | e_stop: 30/30 | reg: 1.60e+01 | :  77%|▊| 77/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 64
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.01e+00 | e_stop: 30/30 | reg: 2.21e+01 | :  52%|▌| 52/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 65
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.00e+00 | e_stop: 30/30 | reg: 1.39e+01 | :  78%|▊| 78/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 66
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 3.19e+00 | e_stop: 30/30 | reg: 1.38e+01 | :  41%|▍| 41/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 67
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 2.13e+01 | :  63%|▋| 63/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 68
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 3.48e+00 | e_stop: 30/30 | reg: 2.10e+01 | :  83%|▊| 83/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 69
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.24e+00 | e_stop: 30/30 | reg: 1.43e+01 | :  32%|▎| 32/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 70
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.23e+00 | e_stop: 30/30 | reg: 1.37e+01 | :  36%|▎| 36/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 71
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 3.21e+00 | e_stop: 30/30 | reg: 1.43e+01 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 72
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 2.75e+00 | e_stop: 30/30 | reg: 2.41e+01 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 73
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.96e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  40%|▍| 40/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 74
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.97e+00 | tst_loss: 2.63e+00 | e_stop: 30/30 | reg: 1.95e+01 | :  57%|▌| 57/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 75
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.01e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 76
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.13e+00 | e_stop: 30/30 | reg: 1.91e+01 | :  42%|▍| 42/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 77
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.19e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  75%|▊| 75/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 78
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.95e+00 | tst_loss: 2.86e+00 | e_stop: 30/30 | reg: 1.35e+01 | :  38%|▍| 38/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 79
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 3.02e+00 | e_stop: 30/30 | reg: 1.39e+01 | :  50%|▌| 50/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 80
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.56e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 81
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.88e+00 | e_stop: 30/30 | reg: 2.00e+01 | :  40%|▍| 40/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 82
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.86e+00 | tst_loss: 3.05e+00 | e_stop: 30/30 | reg: 1.42e+01 | :  73%|▋| 73/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 83
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.95e+00 | tst_loss: 2.70e+00 | e_stop: 30/30 | reg: 1.37e+01 | :  49%|▍| 49/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 84
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 2.98e+00 | e_stop: 30/30 | reg: 1.44e+01 | :  76%|▊| 76/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 85
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 2.89e+00 | e_stop: 30/30 | reg: 1.44e+01 | :  33%|▎| 33/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 86
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.94e+00 | tst_loss: 2.87e+00 | e_stop: 30/30 | reg: 1.39e+01 | :  40%|▍| 40/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 87
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.01e+00 | e_stop: 6/30 | reg: 1.60e+01 | : 100%|█| 100/100 [00:19<

saving model version 0.1
iter: 88
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.13e+00 | e_stop: 30/30 | reg: 1.37e+01 | :  52%|▌| 52/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 89
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.31e+00 | e_stop: 30/30 | reg: 2.14e+01 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 90
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 1.76e+01 | :  33%|▎| 33/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 91
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.16e+00 | e_stop: 30/30 | reg: 2.00e+01 | :  47%|▍| 47/100 [00:09<

Early stopping criteria raised
saving model version 0.1
iter: 92
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.01e+00 | e_stop: 30/30 | reg: 1.64e+01 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 93
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 3.11e+00 | e_stop: 30/30 | reg: 1.56e+01 | :  33%|▎| 33/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 94
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.90e+00 | e_stop: 30/30 | reg: 1.39e+01 | :  35%|▎| 35/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 95
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.86e+00 | tst_loss: 2.91e+00 | e_stop: 30/30 | reg: 1.60e+01 | :  30%|▎| 30/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 96
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 2.94e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  30%|▎| 30/100 [00:07<

Early stopping criteria raised
saving model version 0.1
iter: 97
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 2.81e+00 | e_stop: 30/30 | reg: 1.33e+01 | :  59%|▌| 59/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 98
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.10e+00 | e_stop: 30/30 | reg: 1.39e+01 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
iter: 99
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.82e+00 | e_stop: 30/30 | reg: 1.36e+01 | :  69%|▋| 69/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 100
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.99e+00 | e_stop: 30/30 | reg: 1.40e+01 | :  31%|▎| 31/100 [00:06<

Early stopping criteria raised
saving model version 0.1
-------
--- Processing lmdKAN_Cr
iter: 1
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.45e-01 | tst_loss: 3.49e-01 | e_stop: 30/30 | reg: 1.08e+01 | :  78%|▊| 78/100 [00:36<

Early stopping criteria raised
saving model version 0.1
iter: 2
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.19e-01 | tst_loss: 4.45e-01 | e_stop: 30/30 | reg: 9.71e+00 | :  33%|▎| 33/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 3
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: nan | tst_loss: nan | e_stop: 0/30 | reg: nan | : 100%|█| 100/100 [00:55<00:00,  1.80it/

saving model version 0.1
iter: 4
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.71e-01 | tst_loss: 4.05e-01 | e_stop: 30/30 | reg: 1.06e+01 | :  36%|▎| 36/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 5
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.94e-01 | tst_loss: 3.55e-01 | e_stop: 30/30 | reg: 9.58e+00 | :  58%|▌| 58/100 [00:29<

Early stopping criteria raised
saving model version 0.1
iter: 6
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.27e-01 | tst_loss: 4.05e-01 | e_stop: 30/30 | reg: 8.42e+00 | :  33%|▎| 33/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 7
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.31e-01 | tst_loss: 4.05e-01 | e_stop: 30/30 | reg: 9.91e+00 | :  57%|▌| 57/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 8
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.60e-01 | tst_loss: 4.07e-01 | e_stop: 30/30 | reg: 1.07e+01 | :  32%|▎| 32/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 9
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.58e-01 | tst_loss: 3.74e-01 | e_stop: 30/30 | reg: 1.16e+01 | :  37%|▎| 37/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 10
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.98e-01 | tst_loss: 4.09e-01 | e_stop: 30/30 | reg: 9.79e+00 | :  48%|▍| 48/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 11
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.47e-01 | tst_loss: 3.97e-01 | e_stop: 30/30 | reg: 9.47e+00 | :  37%|▎| 37/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 12
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.51e-01 | tst_loss: 3.58e-01 | e_stop: 30/30 | reg: 1.07e+01 | :  50%|▌| 50/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 13
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.66e-01 | tst_loss: 4.00e-01 | e_stop: 30/30 | reg: 1.13e+01 | :  42%|▍| 42/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 14
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.81e-01 | tst_loss: 4.49e-01 | e_stop: 30/30 | reg: 1.11e+01 | :  38%|▍| 38/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 15
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.50e-01 | tst_loss: 3.67e-01 | e_stop: 30/30 | reg: 1.04e+01 | :  80%|▊| 80/100 [00:41<

Early stopping criteria raised
saving model version 0.1
iter: 16
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.26e-01 | tst_loss: 3.99e-01 | e_stop: 30/30 | reg: 8.66e+00 | :  32%|▎| 32/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 17
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.86e-01 | tst_loss: 4.25e-01 | e_stop: 30/30 | reg: 9.03e+00 | :  80%|▊| 80/100 [00:31<

Early stopping criteria raised
saving model version 0.1
iter: 18
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.68e-01 | tst_loss: 4.65e-01 | e_stop: 30/30 | reg: 1.05e+01 | :  36%|▎| 36/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 19
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.11e-01 | tst_loss: 3.90e-01 | e_stop: 30/30 | reg: 1.10e+01 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 20
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.62e-01 | tst_loss: 4.46e-01 | e_stop: 30/30 | reg: 1.43e+01 | :  54%|▌| 54/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 21
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.13e-01 | tst_loss: 3.79e-01 | e_stop: 0/30 | reg: 8.10e+00 | : 100%|█| 100/100 [00:48<

saving model version 0.1
iter: 22
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.41e-01 | tst_loss: 4.28e-01 | e_stop: 30/30 | reg: 9.56e+00 | :  75%|▊| 75/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 23
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.84e-01 | tst_loss: 4.94e-01 | e_stop: 30/30 | reg: 9.75e+00 | :  52%|▌| 52/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 24
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.88e-01 | tst_loss: 3.38e-01 | e_stop: 30/30 | reg: 1.15e+01 | :  40%|▍| 40/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 25
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.95e-01 | tst_loss: 3.60e-01 | e_stop: 30/30 | reg: 9.48e+00 | :  46%|▍| 46/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 26
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.01e-01 | tst_loss: 4.01e-01 | e_stop: 30/30 | reg: 9.47e+00 | :  59%|▌| 59/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 27
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.52e-01 | tst_loss: 3.36e-01 | e_stop: 30/30 | reg: 1.06e+01 | :  74%|▋| 74/100 [00:36<

Early stopping criteria raised
saving model version 0.1
iter: 28
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.28e-01 | tst_loss: 4.33e-01 | e_stop: 30/30 | reg: 8.54e+00 | :  32%|▎| 32/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 29
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.46e-01 | tst_loss: 3.49e-01 | e_stop: 28/30 | reg: 9.94e+00 | : 100%|█| 100/100 [00:48

saving model version 0.1
iter: 30
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.61e-01 | tst_loss: 3.42e-01 | e_stop: 30/30 | reg: 1.15e+01 | :  43%|▍| 43/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 31
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.38e-01 | tst_loss: 4.45e-01 | e_stop: 30/30 | reg: 7.98e+00 | :  65%|▋| 65/100 [00:33<

Early stopping criteria raised
saving model version 0.1
iter: 32
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.46e-01 | tst_loss: 3.43e-01 | e_stop: 27/30 | reg: 1.28e+01 | : 100%|█| 100/100 [00:50

saving model version 0.1
iter: 33
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.57e-01 | tst_loss: 3.37e-01 | e_stop: 30/30 | reg: 9.47e+00 | :  88%|▉| 88/100 [00:41<

Early stopping criteria raised
saving model version 0.1
iter: 34
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.39e-01 | tst_loss: 3.82e-01 | e_stop: 30/30 | reg: 1.17e+01 | :  38%|▍| 38/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 35
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.16e-01 | tst_loss: 4.19e-01 | e_stop: 30/30 | reg: 8.54e+00 | :  41%|▍| 41/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 36
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.50e-01 | tst_loss: 3.27e-01 | e_stop: 30/30 | reg: 1.22e+01 | :  40%|▍| 40/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 37
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.51e-01 | tst_loss: 3.41e-01 | e_stop: 30/30 | reg: 1.04e+01 | :  74%|▋| 74/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 38
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.03e-01 | tst_loss: 4.35e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  37%|▎| 37/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 39
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.87e-01 | tst_loss: 4.84e-01 | e_stop: 30/30 | reg: 1.25e+01 | :  41%|▍| 41/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 40
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.41e-01 | tst_loss: 3.36e-01 | e_stop: 30/30 | reg: 1.27e+01 | :  43%|▍| 43/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 41
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.99e-01 | tst_loss: 3.77e-01 | e_stop: 30/30 | reg: 9.51e+00 | :  33%|▎| 33/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 42
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.13e-01 | tst_loss: 4.07e-01 | e_stop: 30/30 | reg: 8.43e+00 | :  70%|▋| 70/100 [00:34<

Early stopping criteria raised
saving model version 0.1
iter: 43
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.55e-01 | tst_loss: 3.40e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  69%|▋| 69/100 [00:35<

Early stopping criteria raised
saving model version 0.1
iter: 44
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.67e-01 | tst_loss: 3.79e-01 | e_stop: 30/30 | reg: 9.87e+00 | :  68%|▋| 68/100 [00:35<

Early stopping criteria raised
saving model version 0.1
iter: 45
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.10e-01 | tst_loss: 4.74e-01 | e_stop: 30/30 | reg: 8.49e+00 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 46
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.95e-01 | tst_loss: 3.53e-01 | e_stop: 30/30 | reg: 9.83e+00 | :  48%|▍| 48/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 47
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.45e-01 | tst_loss: 3.52e-01 | e_stop: 30/30 | reg: 1.11e+01 | :  82%|▊| 82/100 [00:41<

Early stopping criteria raised
saving model version 0.1
iter: 48
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.66e-01 | tst_loss: 3.45e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  44%|▍| 44/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 49
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.41e-01 | tst_loss: 3.97e-01 | e_stop: 30/30 | reg: 9.88e+00 | :  32%|▎| 32/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 50
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.47e-01 | tst_loss: 3.35e-01 | e_stop: 30/30 | reg: 1.35e+01 | :  72%|▋| 72/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 51
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.34e-01 | tst_loss: 3.77e-01 | e_stop: 30/30 | reg: 9.24e+00 | :  57%|▌| 57/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 52
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.35e-01 | tst_loss: 3.71e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  75%|▊| 75/100 [00:32<

Early stopping criteria raised
saving model version 0.1
iter: 53
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.60e-01 | tst_loss: 3.46e-01 | e_stop: 30/30 | reg: 1.28e+01 | :  35%|▎| 35/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 54
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.80e-01 | tst_loss: 3.69e-01 | e_stop: 30/30 | reg: 1.10e+01 | :  58%|▌| 58/100 [00:29<

Early stopping criteria raised
saving model version 0.1
iter: 55
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.97e-01 | tst_loss: 4.02e-01 | e_stop: 30/30 | reg: 8.95e+00 | :  80%|▊| 80/100 [00:39<

Early stopping criteria raised
saving model version 0.1
iter: 56
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.47e-01 | tst_loss: 3.73e-01 | e_stop: 30/30 | reg: 1.19e+01 | :  42%|▍| 42/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 57
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.70e-01 | tst_loss: 3.83e-01 | e_stop: 30/30 | reg: 1.09e+01 | :  56%|▌| 56/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 58
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.74e-01 | tst_loss: 3.43e-01 | e_stop: 30/30 | reg: 8.71e+00 | :  56%|▌| 56/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 59
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.40e-01 | tst_loss: 4.55e-01 | e_stop: 30/30 | reg: 9.67e+00 | :  87%|▊| 87/100 [00:44<

Early stopping criteria raised
saving model version 0.1
iter: 60
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.72e-01 | tst_loss: 3.12e-01 | e_stop: 30/30 | reg: 8.56e+00 | :  77%|▊| 77/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 61
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.43e-01 | tst_loss: 3.32e-01 | e_stop: 30/30 | reg: 1.04e+01 | :  79%|▊| 79/100 [00:39<

Early stopping criteria raised
saving model version 0.1
iter: 62
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.32e-01 | tst_loss: 5.16e-01 | e_stop: 30/30 | reg: 1.78e+01 | :  81%|▊| 81/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 63
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.43e-01 | tst_loss: 4.00e-01 | e_stop: 30/30 | reg: 1.19e+01 | :  40%|▍| 40/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 64
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.49e-01 | tst_loss: 4.08e-01 | e_stop: 30/30 | reg: 1.18e+01 | :  76%|▊| 76/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 65
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.46e-01 | tst_loss: 3.69e-01 | e_stop: 30/30 | reg: 9.63e+00 | :  57%|▌| 57/100 [00:29<

Early stopping criteria raised
saving model version 0.1
iter: 66
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.20e-01 | tst_loss: 4.35e-01 | e_stop: 30/30 | reg: 8.85e+00 | :  51%|▌| 51/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 67
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.65e-01 | tst_loss: 4.42e-01 | e_stop: 30/30 | reg: 1.25e+01 | :  75%|▊| 75/100 [00:36<

Early stopping criteria raised
saving model version 0.1
iter: 68
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.76e-01 | tst_loss: 3.88e-01 | e_stop: 30/30 | reg: 1.23e+01 | :  46%|▍| 46/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 69
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.80e-01 | tst_loss: 3.25e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  33%|▎| 33/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 70
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.47e-01 | tst_loss: 3.70e-01 | e_stop: 18/30 | reg: 1.23e+01 | : 100%|█| 100/100 [00:48

saving model version 0.1
iter: 71
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.47e-01 | tst_loss: 3.75e-01 | e_stop: 30/30 | reg: 1.21e+01 | :  44%|▍| 44/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 72
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.82e-01 | tst_loss: 4.65e-01 | e_stop: 30/30 | reg: 9.47e+00 | :  46%|▍| 46/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 73
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.66e-01 | tst_loss: 3.75e-01 | e_stop: 30/30 | reg: 1.08e+01 | :  45%|▍| 45/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 74
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.92e-01 | tst_loss: 3.50e-01 | e_stop: 30/30 | reg: 9.73e+00 | :  64%|▋| 64/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 75
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.72e-01 | tst_loss: 4.44e-01 | e_stop: 30/30 | reg: 1.03e+01 | :  34%|▎| 34/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 76
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.71e-01 | tst_loss: 4.07e-01 | e_stop: 23/30 | reg: 8.16e+00 | : 100%|█| 100/100 [00:47

saving model version 0.1
iter: 77
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.93e-01 | tst_loss: 4.07e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  56%|▌| 56/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 78
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.53e-01 | tst_loss: 3.92e-01 | e_stop: 30/30 | reg: 9.95e+00 | :  39%|▍| 39/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 79
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.84e-01 | tst_loss: 3.46e-01 | e_stop: 30/30 | reg: 9.85e+00 | :  55%|▌| 55/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 80
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.46e-01 | tst_loss: 3.87e-01 | e_stop: 30/30 | reg: 1.12e+01 | :  67%|▋| 67/100 [00:33<

Early stopping criteria raised
saving model version 0.1
iter: 81
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.63e-01 | tst_loss: 4.02e-01 | e_stop: 30/30 | reg: 1.13e+01 | :  32%|▎| 32/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 82
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.00e-01 | tst_loss: 3.99e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  64%|▋| 64/100 [00:31<

Early stopping criteria raised
saving model version 0.1
iter: 83
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.27e-01 | tst_loss: 3.99e-01 | e_stop: 30/30 | reg: 8.63e+00 | :  34%|▎| 34/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 84
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.80e-01 | tst_loss: 4.05e-01 | e_stop: 30/30 | reg: 1.07e+01 | :  69%|▋| 69/100 [00:34<

Early stopping criteria raised
saving model version 0.1
iter: 85
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.09e-01 | tst_loss: 4.44e-01 | e_stop: 30/30 | reg: 8.62e+00 | :  42%|▍| 42/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 86
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.12e-01 | tst_loss: 3.14e-01 | e_stop: 30/30 | reg: 1.00e+01 | :  56%|▌| 56/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 87
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.62e-01 | tst_loss: 3.60e-01 | e_stop: 30/30 | reg: 1.10e+01 | :  65%|▋| 65/100 [00:29<

Early stopping criteria raised
saving model version 0.1
iter: 88
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.93e-01 | tst_loss: 4.62e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  34%|▎| 34/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 89
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.73e-01 | tst_loss: 4.35e-01 | e_stop: 30/30 | reg: 1.30e+01 | :  42%|▍| 42/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 90
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.38e-01 | tst_loss: 4.29e-01 | e_stop: 3/30 | reg: 1.14e+01 | : 100%|█| 100/100 [00:48<

saving model version 0.1
iter: 91
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.13e-01 | tst_loss: 4.23e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  32%|▎| 32/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 92
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.50e-01 | tst_loss: 3.02e-01 | e_stop: 30/30 | reg: 1.20e+01 | :  43%|▍| 43/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 93
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.09e-01 | tst_loss: 4.46e-01 | e_stop: 30/30 | reg: 8.61e+00 | :  43%|▍| 43/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 94
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.18e-01 | tst_loss: 4.45e-01 | e_stop: 30/30 | reg: 8.74e+00 | :  59%|▌| 59/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 95
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.98e-01 | tst_loss: 4.21e-01 | e_stop: 30/30 | reg: 8.17e+00 | :  67%|▋| 67/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 96
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.43e-01 | tst_loss: 3.69e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  71%|▋| 71/100 [00:36<

Early stopping criteria raised
saving model version 0.1
iter: 97
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.66e-01 | tst_loss: 3.56e-01 | e_stop: 5/30 | reg: 1.13e+01 | : 100%|█| 100/100 [00:50<

saving model version 0.1
iter: 98
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.56e-01 | tst_loss: 3.85e-01 | e_stop: 30/30 | reg: 1.05e+01 | :  88%|▉| 88/100 [00:43<

Early stopping criteria raised
saving model version 0.1
iter: 99
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 4.10e-01 | tst_loss: 4.26e-01 | e_stop: 30/30 | reg: 8.37e+00 | :  34%|▎| 34/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 100
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.49e-01 | tst_loss: 3.93e-01 | e_stop: 30/30 | reg: 1.07e+01 | :  59%|▌| 59/100 [00:29<

Early stopping criteria raised
saving model version 0.1
-------
--- Processing lmdKAN_Cu
iter: 1
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.93e-01 | tst_loss: 7.62e-01 | e_stop: 14/30 | reg: 1.19e+01 | : 100%|█| 100/100 [00:51

saving model version 0.1
iter: 2
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.27e-01 | tst_loss: 7.73e-01 | e_stop: 30/30 | reg: 1.12e+01 | :  94%|▉| 94/100 [00:45<

Early stopping criteria raised
saving model version 0.1
iter: 3
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.82e-01 | tst_loss: 7.75e-01 | e_stop: 30/30 | reg: 2.30e+01 | :  84%|▊| 84/100 [00:44<

Early stopping criteria raised
saving model version 0.1
iter: 4
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.43e-01 | tst_loss: 7.17e-01 | e_stop: 30/30 | reg: 9.97e+00 | :  35%|▎| 35/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 5
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.38e-01 | tst_loss: 7.25e-01 | e_stop: 30/30 | reg: 1.54e+01 | :  49%|▍| 49/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 6
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.28e-01 | tst_loss: 7.28e-01 | e_stop: 30/30 | reg: 1.86e+01 | :  74%|▋| 74/100 [00:31<

Early stopping criteria raised
saving model version 0.1
iter: 7
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.01e-01 | tst_loss: 8.37e-01 | e_stop: 30/30 | reg: 9.35e+00 | :  48%|▍| 48/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 8
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.11e-01 | tst_loss: 8.71e-01 | e_stop: 30/30 | reg: 1.85e+01 | :  48%|▍| 48/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 9
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 8.01e-01 | e_stop: 30/30 | reg: 9.22e+00 | :  40%|▍| 40/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 10
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.01e-01 | tst_loss: 8.22e-01 | e_stop: 30/30 | reg: 1.15e+01 | :  33%|▎| 33/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 11
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.32e-01 | tst_loss: 7.11e-01 | e_stop: 30/30 | reg: 1.81e+01 | :  37%|▎| 37/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 12
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.18e-01 | tst_loss: 7.67e-01 | e_stop: 30/30 | reg: 1.18e+01 | :  32%|▎| 32/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 13
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.37e-01 | tst_loss: 7.55e-01 | e_stop: 30/30 | reg: 9.81e+00 | :  33%|▎| 33/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 14
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.94e-01 | tst_loss: 7.93e-01 | e_stop: 30/30 | reg: 1.16e+01 | :  53%|▌| 53/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 15
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.32e-01 | tst_loss: 7.54e-01 | e_stop: 30/30 | reg: 1.09e+01 | :  37%|▎| 37/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 16
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.36e-01 | tst_loss: 6.59e-01 | e_stop: 30/30 | reg: 1.83e+01 | :  94%|▉| 94/100 [00:40<

Early stopping criteria raised
saving model version 0.1
iter: 17
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.95e-01 | tst_loss: 8.43e-01 | e_stop: 30/30 | reg: 1.05e+01 | :  67%|▋| 67/100 [00:29<

Early stopping criteria raised
saving model version 0.1
iter: 18
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.14e-01 | tst_loss: 8.83e-01 | e_stop: 30/30 | reg: 1.10e+01 | :  35%|▎| 35/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 19
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.20e-01 | tst_loss: 6.95e-01 | e_stop: 30/30 | reg: 1.08e+01 | :  40%|▍| 40/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 20
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.23e-01 | tst_loss: 7.64e-01 | e_stop: 30/30 | reg: 1.13e+01 | :  43%|▍| 43/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 21
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.42e-01 | tst_loss: 8.07e-01 | e_stop: 30/30 | reg: 2.29e+01 | :  42%|▍| 42/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 22
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 7.25e-01 | e_stop: 30/30 | reg: 1.11e+01 | :  69%|▋| 69/100 [00:34<

Early stopping criteria raised
saving model version 0.1
iter: 23
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.23e-01 | tst_loss: 8.26e-01 | e_stop: 30/30 | reg: 1.18e+01 | :  38%|▍| 38/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 24
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.44e-01 | tst_loss: 6.61e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 25
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.55e-01 | tst_loss: 7.32e-01 | e_stop: 30/30 | reg: 2.35e+01 | :  89%|▉| 89/100 [00:45<

Early stopping criteria raised
saving model version 0.1
iter: 26
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.59e-01 | tst_loss: 7.46e-01 | e_stop: 30/30 | reg: 1.20e+01 | :  38%|▍| 38/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 27
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.14e-01 | tst_loss: 6.84e-01 | e_stop: 30/30 | reg: 1.13e+01 | :  67%|▋| 67/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 28
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.43e-01 | tst_loss: 7.07e-01 | e_stop: 30/30 | reg: 1.63e+01 | :  52%|▌| 52/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 29
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.21e-01 | tst_loss: 7.75e-01 | e_stop: 30/30 | reg: 9.31e+00 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 30
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.22e-01 | tst_loss: 7.67e-01 | e_stop: 30/30 | reg: 9.91e+00 | :  38%|▍| 38/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 31
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.23e-01 | tst_loss: 7.12e-01 | e_stop: 30/30 | reg: 1.05e+01 | :  52%|▌| 52/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 32
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.26e-01 | tst_loss: 8.10e-01 | e_stop: 30/30 | reg: 2.02e+01 | :  68%|▋| 68/100 [00:34<

Early stopping criteria raised
saving model version 0.1
iter: 33
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.25e-01 | tst_loss: 7.41e-01 | e_stop: 30/30 | reg: 9.38e+00 | :  32%|▎| 32/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 34
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.26e-01 | tst_loss: 7.85e-01 | e_stop: 30/30 | reg: 1.74e+01 | :  50%|▌| 50/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 35
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.06e-01 | tst_loss: 7.24e-01 | e_stop: 30/30 | reg: 1.89e+01 | :  67%|▋| 67/100 [00:34<

Early stopping criteria raised
saving model version 0.1
iter: 36
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.13e-01 | tst_loss: 7.74e-01 | e_stop: 30/30 | reg: 1.41e+01 | :  38%|▍| 38/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 37
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.09e-01 | tst_loss: 7.00e-01 | e_stop: 30/30 | reg: 1.20e+01 | :  72%|▋| 72/100 [00:35<

Early stopping criteria raised
saving model version 0.1
iter: 38
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.21e-01 | tst_loss: 8.27e-01 | e_stop: 30/30 | reg: 8.53e+00 | :  32%|▎| 32/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 39
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.01e-01 | tst_loss: 7.78e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  75%|▊| 75/100 [00:38<

Early stopping criteria raised
saving model version 0.1
iter: 40
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.22e-01 | tst_loss: 6.38e-01 | e_stop: 30/30 | reg: 1.13e+01 | :  38%|▍| 38/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 41
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 6.89e-01 | e_stop: 30/30 | reg: 1.80e+01 | :  78%|▊| 78/100 [00:33<

Early stopping criteria raised
saving model version 0.1
iter: 42
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.21e-01 | tst_loss: 7.32e-01 | e_stop: 30/30 | reg: 1.88e+01 | :  79%|▊| 79/100 [00:39<

Early stopping criteria raised
saving model version 0.1
iter: 43
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.28e-01 | tst_loss: 6.77e-01 | e_stop: 29/30 | reg: 9.09e+00 | : 100%|█| 100/100 [00:49

saving model version 0.1
iter: 44
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.25e-01 | tst_loss: 7.81e-01 | e_stop: 30/30 | reg: 2.06e+01 | :  45%|▍| 45/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 45
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.14e-01 | tst_loss: 7.89e-01 | e_stop: 30/30 | reg: 2.05e+01 | :  47%|▍| 47/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 46
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.42e-01 | tst_loss: 7.30e-01 | e_stop: 30/30 | reg: 9.90e+00 | :  34%|▎| 34/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 47
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 6.97e-01 | tst_loss: 7.28e-01 | e_stop: 30/30 | reg: 1.19e+01 | :  66%|▋| 66/100 [00:32<

Early stopping criteria raised
saving model version 0.1
iter: 48
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.30e-01 | tst_loss: 6.40e-01 | e_stop: 30/30 | reg: 1.01e+01 | :  64%|▋| 64/100 [00:33<

Early stopping criteria raised
saving model version 0.1
iter: 49
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.21e-01 | tst_loss: 8.57e-01 | e_stop: 30/30 | reg: 9.84e+00 | :  42%|▍| 42/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 50
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.30e-01 | tst_loss: 6.82e-01 | e_stop: 30/30 | reg: 1.03e+01 | :  53%|▌| 53/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 51
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.23e-01 | tst_loss: 7.73e-01 | e_stop: 30/30 | reg: 1.63e+01 | :  59%|▌| 59/100 [00:32<

Early stopping criteria raised
saving model version 0.1
iter: 52
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.00e-01 | tst_loss: 7.89e-01 | e_stop: 30/30 | reg: 1.14e+01 | :  36%|▎| 36/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 53
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.28e-01 | tst_loss: 7.28e-01 | e_stop: 30/30 | reg: 2.01e+01 | :  43%|▍| 43/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 54
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.21e-01 | tst_loss: 7.69e-01 | e_stop: 29/30 | reg: 1.66e+01 | : 100%|█| 100/100 [00:49

saving model version 0.1
iter: 55
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.27e-01 | tst_loss: 6.64e-01 | e_stop: 30/30 | reg: 1.11e+01 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 56
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.08e-01 | tst_loss: 6.85e-01 | e_stop: 30/30 | reg: 1.30e+01 | :  50%|▌| 50/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 57
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.31e-01 | tst_loss: 7.20e-01 | e_stop: 30/30 | reg: 8.49e+00 | :  40%|▍| 40/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 58
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.22e-01 | tst_loss: 7.17e-01 | e_stop: 30/30 | reg: 1.08e+01 | :  36%|▎| 36/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 59
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.08e-01 | tst_loss: 8.76e-01 | e_stop: 30/30 | reg: 1.84e+01 | :  67%|▋| 67/100 [00:34<

Early stopping criteria raised
saving model version 0.1
iter: 60
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.32e-01 | tst_loss: 6.56e-01 | e_stop: 30/30 | reg: 1.89e+01 | :  86%|▊| 86/100 [00:43<

Early stopping criteria raised
saving model version 0.1
iter: 61
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.23e-01 | tst_loss: 6.70e-01 | e_stop: 30/30 | reg: 1.06e+01 | :  33%|▎| 33/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 62
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.32e-01 | tst_loss: 8.33e-01 | e_stop: 30/30 | reg: 1.90e+01 | :  61%|▌| 61/100 [00:31<

Early stopping criteria raised
saving model version 0.1
iter: 63
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 8.02e-01 | tst_loss: 8.39e-01 | e_stop: 20/30 | reg: 1.99e+01 | : 100%|█| 100/100 [00:51

saving model version 0.1
iter: 64
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.20e-01 | tst_loss: 7.29e-01 | e_stop: 30/30 | reg: 1.05e+01 | :  78%|▊| 78/100 [00:38<

Early stopping criteria raised
saving model version 0.1
iter: 65
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.19e-01 | tst_loss: 8.05e-01 | e_stop: 30/30 | reg: 1.11e+01 | :  43%|▍| 43/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 66
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.53e-01 | tst_loss: 7.30e-01 | e_stop: 30/30 | reg: 2.12e+01 | :  51%|▌| 51/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 67
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.08e-01 | tst_loss: 8.61e-01 | e_stop: 30/30 | reg: 1.53e+01 | :  53%|▌| 53/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 68
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.27e-01 | tst_loss: 7.28e-01 | e_stop: 30/30 | reg: 1.12e+01 | :  57%|▌| 57/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 69
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.20e-01 | tst_loss: 6.82e-01 | e_stop: 30/30 | reg: 1.43e+01 | :  50%|▌| 50/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 70
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.19e-01 | tst_loss: 7.64e-01 | e_stop: 30/30 | reg: 1.95e+01 | :  54%|▌| 54/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 71
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.41e-01 | tst_loss: 8.18e-01 | e_stop: 30/30 | reg: 1.24e+01 | :  55%|▌| 55/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 72
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.39e-01 | tst_loss: 6.81e-01 | e_stop: 30/30 | reg: 1.04e+01 | :  42%|▍| 42/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 73
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.34e-01 | tst_loss: 7.69e-01 | e_stop: 30/30 | reg: 7.98e+00 | :  32%|▎| 32/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 74
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.28e-01 | tst_loss: 7.72e-01 | e_stop: 30/30 | reg: 9.58e+00 | :  46%|▍| 46/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 75
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.27e-01 | tst_loss: 7.28e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  39%|▍| 39/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 76
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.86e-01 | tst_loss: 9.55e-01 | e_stop: 30/30 | reg: 1.84e+01 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 77
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.07e-01 | tst_loss: 7.25e-01 | e_stop: 30/30 | reg: 1.91e+01 | :  79%|▊| 79/100 [00:40<

Early stopping criteria raised
saving model version 0.1
iter: 78
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.16e-01 | tst_loss: 6.95e-01 | e_stop: 30/30 | reg: 1.11e+01 | :  53%|▌| 53/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 79
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.17e-01 | tst_loss: 7.04e-01 | e_stop: 30/30 | reg: 1.02e+01 | :  67%|▋| 67/100 [00:32<

Early stopping criteria raised
saving model version 0.1
iter: 80
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.25e-01 | tst_loss: 8.13e-01 | e_stop: 30/30 | reg: 1.21e+01 | :  35%|▎| 35/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 81
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.19e-01 | tst_loss: 5.81e-01 | e_stop: 30/30 | reg: 1.12e+01 | :  49%|▍| 49/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 82
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.61e-01 | tst_loss: 7.37e-01 | e_stop: 8/30 | reg: 2.00e+01 | : 100%|█| 100/100 [00:51<

saving model version 0.1
iter: 83
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.40e-01 | tst_loss: 8.00e-01 | e_stop: 30/30 | reg: 1.37e+01 | :  50%|▌| 50/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 84
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.42e-01 | tst_loss: 7.29e-01 | e_stop: 30/30 | reg: 8.90e+00 | :  39%|▍| 39/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 85
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.12e-01 | tst_loss: 7.56e-01 | e_stop: 30/30 | reg: 1.72e+01 | :  65%|▋| 65/100 [00:33<

Early stopping criteria raised
saving model version 0.1
iter: 86
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.29e-01 | tst_loss: 6.75e-01 | e_stop: 30/30 | reg: 1.03e+01 | :  89%|▉| 89/100 [00:43<

Early stopping criteria raised
saving model version 0.1
iter: 87
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.10e-01 | tst_loss: 8.22e-01 | e_stop: 30/30 | reg: 1.09e+01 | :  64%|▋| 64/100 [00:32<

Early stopping criteria raised
saving model version 0.1
iter: 88
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 8.32e-01 | tst_loss: 8.69e-01 | e_stop: 30/30 | reg: 2.29e+01 | :  33%|▎| 33/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 89
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.33e-01 | tst_loss: 7.44e-01 | e_stop: 30/30 | reg: 9.59e+00 | :  53%|▌| 53/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 90
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.06e-01 | tst_loss: 7.15e-01 | e_stop: 30/30 | reg: 1.56e+01 | :  40%|▍| 40/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 91
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.09e-01 | tst_loss: 7.27e-01 | e_stop: 30/30 | reg: 1.94e+01 | :  73%|▋| 73/100 [00:36<

Early stopping criteria raised
saving model version 0.1
iter: 92
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.23e-01 | tst_loss: 6.54e-01 | e_stop: 30/30 | reg: 1.07e+01 | :  65%|▋| 65/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 93
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.33e-01 | tst_loss: 7.22e-01 | e_stop: 30/30 | reg: 1.09e+01 | :  43%|▍| 43/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 94
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.25e-01 | tst_loss: 7.04e-01 | e_stop: 30/30 | reg: 1.84e+01 | :  74%|▋| 74/100 [00:38<

Early stopping criteria raised
saving model version 0.1
iter: 95
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.29e-01 | tst_loss: 7.50e-01 | e_stop: 30/30 | reg: 1.35e+01 | :  39%|▍| 39/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 96
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.25e-01 | tst_loss: 7.52e-01 | e_stop: 30/30 | reg: 9.97e+00 | :  47%|▍| 47/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 97
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.06e-01 | tst_loss: 1.03e+00 | e_stop: 30/30 | reg: 1.35e+01 | :  39%|▍| 39/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 98
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.13e-01 | tst_loss: 6.67e-01 | e_stop: 30/30 | reg: 1.08e+01 | :  61%|▌| 61/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 99
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.02e-01 | tst_loss: 7.50e-01 | e_stop: 30/30 | reg: 1.76e+01 | :  83%|▊| 83/100 [00:42<

Early stopping criteria raised
saving model version 0.1
iter: 100
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 7.23e-01 | tst_loss: 8.58e-01 | e_stop: 30/30 | reg: 1.07e+01 | :  32%|▎| 32/100 [00:10<

Early stopping criteria raised
saving model version 0.1
-------
--- Processing lmdKAN_Ni
iter: 1
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 1.57e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 2
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.58e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 7.07e-01 | :  75%|▊| 75/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 3
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.67e+00 | e_stop: 30/30 | reg: 1.33e+01 | :  40%|▍| 40/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 4
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.66e+00 | e_stop: 30/30 | reg: 1.07e+01 | :  37%|▎| 37/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 5
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.59e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 1.05e-01 | :  31%|▎| 31/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 6
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.53e+00 | e_stop: 30/30 | reg: 8.36e+00 | :  67%|▋| 67/100 [00:33<

Early stopping criteria raised
saving model version 0.1
iter: 7
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.65e+00 | e_stop: 30/30 | reg: 1.09e+01 | :  32%|▎| 32/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 8
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.58e+00 | tst_loss: 1.53e+00 | e_stop: 30/30 | reg: 5.33e-01 | :  30%|▎| 30/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 9
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 1.20e+01 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 10
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.55e+00 | e_stop: 30/30 | reg: 1.01e+01 | :  37%|▎| 37/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 11
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.54e+00 | e_stop: 30/30 | reg: 7.10e+00 | :  34%|▎| 34/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 12
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.42e+00 | e_stop: 30/30 | reg: 6.50e+00 | :  35%|▎| 35/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 13
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.52e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 6.24e+00 | :  34%|▎| 34/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 14
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.45e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 1.06e+01 | :  30%|▎| 30/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 15
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.65e+00 | e_stop: 30/30 | reg: 9.88e+00 | :  44%|▍| 44/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 16
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 9.81e+00 | :  39%|▍| 39/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 17
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.52e+00 | tst_loss: 1.49e+00 | e_stop: 30/30 | reg: 7.25e+00 | :  40%|▍| 40/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 18
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.59e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 1.07e+00 | :  31%|▎| 31/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 19
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 7.82e+00 | :  71%|▋| 71/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 20
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.56e+00 | tst_loss: 1.62e+00 | e_stop: 30/30 | reg: 5.78e-01 | :  60%|▌| 60/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 21
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.45e+00 | tst_loss: 1.55e+00 | e_stop: 30/30 | reg: 1.10e+01 | :  31%|▎| 31/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 22
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 1.17e+01 | :  69%|▋| 69/100 [00:38<

Early stopping criteria raised
saving model version 0.1
iter: 23
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.44e+00 | tst_loss: 1.67e+00 | e_stop: 30/30 | reg: 1.00e+01 | :  50%|▌| 50/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 24
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.49e+00 | e_stop: 30/30 | reg: 1.27e+01 | :  70%|▋| 70/100 [00:35<

Early stopping criteria raised
saving model version 0.1
iter: 25
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.77e+00 | e_stop: 30/30 | reg: 1.14e+01 | :  35%|▎| 35/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 26
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.54e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 6.38e+00 | :  34%|▎| 34/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 27
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 1.24e+01 | :  45%|▍| 45/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 28
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.52e+00 | tst_loss: 1.68e+00 | e_stop: 30/30 | reg: 6.74e+00 | :  33%|▎| 33/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 29
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.70e+00 | e_stop: 30/30 | reg: 1.25e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 30
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 8.90e+00 | :  44%|▍| 44/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 31
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.62e+00 | e_stop: 30/30 | reg: 9.06e+00 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 32
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.70e+00 | e_stop: 30/30 | reg: 1.16e+01 | :  30%|▎| 30/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 33
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 7.45e+00 | :  31%|▎| 31/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 34
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.45e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 1.28e+01 | :  31%|▎| 31/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 35
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.49e+00 | e_stop: 30/30 | reg: 1.07e+01 | :  32%|▎| 32/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 36
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.44e+00 | tst_loss: 1.55e+00 | e_stop: 30/30 | reg: 1.89e+01 | :  41%|▍| 41/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 37
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.45e+00 | tst_loss: 1.67e+00 | e_stop: 30/30 | reg: 1.06e+01 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 38
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.71e+00 | e_stop: 30/30 | reg: 9.18e+00 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 39
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.53e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 6.97e+00 | :  30%|▎| 30/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 40
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.63e+00 | e_stop: 30/30 | reg: 1.07e+01 | :  34%|▎| 34/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 41
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.44e+00 | tst_loss: 1.71e+00 | e_stop: 30/30 | reg: 2.04e+01 | :  30%|▎| 30/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 42
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.52e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 6.24e+00 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 43
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.42e+00 | tst_loss: 1.71e+00 | e_stop: 30/30 | reg: 1.20e+01 | :  60%|▌| 60/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 44
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.43e+00 | e_stop: 30/30 | reg: 5.90e+00 | :  86%|▊| 86/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 45
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.76e+00 | e_stop: 30/30 | reg: 1.21e+01 | :  31%|▎| 31/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 46
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.73e+00 | e_stop: 30/30 | reg: 1.04e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 47
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.57e+00 | e_stop: 30/30 | reg: 1.04e+01 | :  38%|▍| 38/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 48
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.57e+00 | e_stop: 30/30 | reg: 8.37e+00 | :  34%|▎| 34/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 49
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.62e+00 | e_stop: 30/30 | reg: 8.12e+00 | :  32%|▎| 32/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 50
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 9.46e+00 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 51
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.53e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 6.02e+00 | :  35%|▎| 35/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 52
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 1.58e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 53
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.64e+00 | e_stop: 30/30 | reg: 1.01e+01 | :  32%|▎| 32/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 54
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.57e+00 | e_stop: 30/30 | reg: 7.93e+00 | :  34%|▎| 34/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 55
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.57e+00 | tst_loss: 1.68e+00 | e_stop: 30/30 | reg: 5.65e-01 | :  30%|▎| 30/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 56
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.46e+00 | e_stop: 30/30 | reg: 9.31e+00 | :  91%|▉| 91/100 [00:48<

Early stopping criteria raised
saving model version 0.1
iter: 57
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.42e+00 | e_stop: 30/30 | reg: 1.10e+01 | :  39%|▍| 39/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 58
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.45e+00 | tst_loss: 1.71e+00 | e_stop: 30/30 | reg: 1.47e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 59
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.58e+00 | tst_loss: 1.57e+00 | e_stop: 30/30 | reg: 3.68e-01 | :  30%|▎| 30/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 60
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.64e+00 | e_stop: 30/30 | reg: 9.34e+00 | :  34%|▎| 34/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 61
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.48e+00 | e_stop: 30/30 | reg: 1.06e+01 | :  41%|▍| 41/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 62
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.72e+00 | e_stop: 30/30 | reg: 1.87e+01 | :  35%|▎| 35/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 63
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.45e+00 | e_stop: 30/30 | reg: 1.11e+01 | :  36%|▎| 36/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 64
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.45e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 1.05e+01 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 65
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.58e+00 | tst_loss: 1.66e+00 | e_stop: 30/30 | reg: 5.13e-01 | :  31%|▎| 31/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 66
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.67e+00 | e_stop: 30/30 | reg: 8.65e+00 | :  44%|▍| 44/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 67
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.72e+00 | e_stop: 30/30 | reg: 1.02e+01 | :  35%|▎| 35/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 68
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.46e+00 | tst_loss: 1.97e+00 | e_stop: 30/30 | reg: 1.34e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 69
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.79e+00 | e_stop: 30/30 | reg: 1.53e+01 | :  31%|▎| 31/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 70
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.72e+00 | e_stop: 30/30 | reg: 1.04e+01 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 71
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 1.29e+01 | :  38%|▍| 38/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 72
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.54e+00 | tst_loss: 1.36e+00 | e_stop: 30/30 | reg: 6.54e+00 | :  67%|▋| 67/100 [00:32<

Early stopping criteria raised
saving model version 0.1
iter: 73
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.52e+00 | tst_loss: 1.61e+00 | e_stop: 30/30 | reg: 6.19e+00 | :  43%|▍| 43/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 74
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.58e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 5.87e-01 | :  55%|▌| 55/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 75
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 1.15e+01 | :  49%|▍| 49/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 76
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.59e+00 | e_stop: 30/30 | reg: 9.89e+00 | :  52%|▌| 52/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 77
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.56e+00 | tst_loss: 1.72e+00 | e_stop: 30/30 | reg: 6.23e-01 | :  75%|▊| 75/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 78
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.47e+00 | e_stop: 30/30 | reg: 1.05e+01 | :  35%|▎| 35/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 79
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.57e+00 | tst_loss: 1.67e+00 | e_stop: 30/30 | reg: 3.56e-01 | :  30%|▎| 30/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 80
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.60e+00 | tst_loss: 1.45e+00 | e_stop: 30/30 | reg: 1.32e+00 | :  30%|▎| 30/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 81
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.69e+00 | e_stop: 30/30 | reg: 1.08e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 82
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.66e+00 | e_stop: 30/30 | reg: 9.82e+00 | :  35%|▎| 35/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 83
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.53e+00 | tst_loss: 1.42e+00 | e_stop: 30/30 | reg: 7.13e+00 | :  31%|▎| 31/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 84
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.52e+00 | tst_loss: 1.56e+00 | e_stop: 30/30 | reg: 6.39e+00 | :  31%|▎| 31/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 85
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 2.52e+00 | e_stop: 30/30 | reg: 1.38e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 86
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.56e+00 | tst_loss: 1.41e+00 | e_stop: 30/30 | reg: 8.44e+00 | :  36%|▎| 36/100 [00:08<

Early stopping criteria raised
saving model version 0.1
iter: 87
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.52e+00 | tst_loss: 1.61e+00 | e_stop: 30/30 | reg: 8.75e+00 | :  67%|▋| 67/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 88
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.53e+00 | tst_loss: 1.72e+00 | e_stop: 30/30 | reg: 6.48e+00 | :  41%|▍| 41/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 89
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.45e+00 | tst_loss: 1.86e+00 | e_stop: 30/30 | reg: 1.16e+01 | :  32%|▎| 32/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 90
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.48e+00 | e_stop: 30/30 | reg: 1.07e+01 | :  31%|▎| 31/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 91
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.67e+00 | e_stop: 30/30 | reg: 1.33e+01 | :  30%|▎| 30/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 92
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.49e+00 | tst_loss: 1.51e+00 | e_stop: 30/30 | reg: 1.11e+01 | :  30%|▎| 30/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 93
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.53e+00 | tst_loss: 1.64e+00 | e_stop: 30/30 | reg: 6.38e+00 | :  30%|▎| 30/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 94
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.51e+00 | tst_loss: 1.60e+00 | e_stop: 30/30 | reg: 8.08e+00 | :  33%|▎| 33/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 95
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.48e+00 | tst_loss: 1.42e+00 | e_stop: 30/30 | reg: 1.03e+01 | :  49%|▍| 49/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 96
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.47e+00 | tst_loss: 1.62e+00 | e_stop: 30/30 | reg: 1.06e+01 | :  31%|▎| 31/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 97
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.53e+00 | tst_loss: 1.52e+00 | e_stop: 30/30 | reg: 6.42e+00 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 98
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.50e+00 | tst_loss: 1.76e+00 | e_stop: 30/30 | reg: 1.07e+01 | :  34%|▎| 34/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 99
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.56e+00 | tst_loss: 1.65e+00 | e_stop: 30/30 | reg: 2.08e-01 | :  30%|▎| 30/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 100
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 1.60e+00 | tst_loss: 1.58e+00 | e_stop: 30/30 | reg: 2.22e-01 | :  30%|▎| 30/100 [00:12<

Early stopping criteria raised
saving model version 0.1
-------
--- Processing lmdKAN_NO3
iter: 1
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.04e+00 | tst_loss: 3.29e+00 | e_stop: 30/30 | reg: 3.79e+01 | :  74%|▋| 74/100 [00:38<

Early stopping criteria raised
saving model version 0.1
iter: 2
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.77e+00 | tst_loss: 3.26e+00 | e_stop: 30/30 | reg: 3.10e+01 | :  36%|▎| 36/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 3
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 2.96e+00 | e_stop: 30/30 | reg: 3.35e+01 | :  44%|▍| 44/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 4
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.01e+00 | tst_loss: 4.23e+00 | e_stop: 10/30 | reg: 4.03e+01 | : 100%|█| 100/100 [00:50

saving model version 0.1
iter: 5
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.84e+00 | tst_loss: 3.02e+00 | e_stop: 30/30 | reg: 2.65e+01 | :  60%|▌| 60/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 6
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.78e+00 | tst_loss: 2.99e+00 | e_stop: 30/30 | reg: 3.78e+01 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 7
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.08e+00 | e_stop: 30/30 | reg: 5.07e+01 | :  53%|▌| 53/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 8
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.39e+00 | e_stop: 30/30 | reg: 3.81e+01 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 9
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.91e+00 | e_stop: 30/30 | reg: 3.68e+01 | :  47%|▍| 47/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 10
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.20e+00 | e_stop: 30/30 | reg: 2.95e+01 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 11
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 2.88e+00 | e_stop: 30/30 | reg: 4.33e+01 | :  46%|▍| 46/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 12
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 2.95e+00 | e_stop: 30/30 | reg: 4.32e+01 | :  40%|▍| 40/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 13
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.77e+00 | tst_loss: 3.25e+00 | e_stop: 28/30 | reg: 3.36e+01 | : 100%|█| 100/100 [00:50

saving model version 0.1
iter: 14
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.97e+00 | tst_loss: 3.26e+00 | e_stop: 30/30 | reg: 3.31e+01 | :  33%|▎| 33/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 15
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.79e+00 | tst_loss: 3.17e+00 | e_stop: 30/30 | reg: 3.78e+01 | :  46%|▍| 46/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 16
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.78e+00 | tst_loss: 3.18e+00 | e_stop: 30/30 | reg: 3.06e+01 | :  31%|▎| 31/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 17
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.94e+00 | tst_loss: 3.08e+00 | e_stop: 3/30 | reg: 2.81e+01 | : 100%|█| 100/100 [00:50<

saving model version 0.1
iter: 18
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.04e+00 | tst_loss: 3.00e+00 | e_stop: 30/30 | reg: 3.83e+01 | :  76%|▊| 76/100 [00:39<

Early stopping criteria raised
saving model version 0.1
iter: 19
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.83e+00 | tst_loss: 3.31e+00 | e_stop: 30/30 | reg: 3.40e+01 | :  37%|▎| 37/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 20
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.82e+00 | tst_loss: 2.87e+00 | e_stop: 30/30 | reg: 3.35e+01 | :  77%|▊| 77/100 [00:39<

Early stopping criteria raised
saving model version 0.1
iter: 21
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.78e+00 | tst_loss: 3.33e+00 | e_stop: 30/30 | reg: 3.20e+01 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 22
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.94e+00 | tst_loss: 2.97e+00 | e_stop: 30/30 | reg: 3.81e+01 | :  72%|▋| 72/100 [00:37<

Early stopping criteria raised
saving model version 0.1
iter: 23
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.74e+00 | tst_loss: 3.37e+00 | e_stop: 30/30 | reg: 3.76e+01 | :  37%|▎| 37/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 24
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 2.98e+00 | e_stop: 30/30 | reg: 3.48e+01 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 25
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.70e+00 | e_stop: 30/30 | reg: 3.93e+01 | :  68%|▋| 68/100 [00:35<

Early stopping criteria raised
saving model version 0.1
iter: 26
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.78e+00 | tst_loss: 3.35e+00 | e_stop: 30/30 | reg: 3.21e+01 | :  34%|▎| 34/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 27
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.84e+00 | tst_loss: 2.88e+00 | e_stop: 30/30 | reg: 3.82e+01 | :  59%|▌| 59/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 28
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.81e+00 | tst_loss: 3.65e+00 | e_stop: 30/30 | reg: 2.69e+01 | :  37%|▎| 37/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 29
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.87e+00 | tst_loss: 3.37e+00 | e_stop: 30/30 | reg: 4.02e+01 | :  65%|▋| 65/100 [00:33<

Early stopping criteria raised
saving model version 0.1
iter: 30
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.95e+00 | tst_loss: 3.25e+00 | e_stop: 30/30 | reg: 2.93e+01 | :  31%|▎| 31/100 [00:15<

Early stopping criteria raised
saving model version 0.1
iter: 31
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.22e+00 | e_stop: 30/30 | reg: 2.42e+01 | :  32%|▎| 32/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 32
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.10e+00 | tst_loss: 3.37e+00 | e_stop: 2/30 | reg: 4.54e+01 | : 100%|█| 100/100 [00:50<

saving model version 0.1
iter: 33
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.72e+00 | tst_loss: 3.52e+00 | e_stop: 30/30 | reg: 3.19e+01 | :  35%|▎| 35/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 34
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.96e+00 | tst_loss: 2.76e+00 | e_stop: 30/30 | reg: 5.11e+01 | :  59%|▌| 59/100 [00:32<

Early stopping criteria raised
saving model version 0.1
iter: 35
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: nan | tst_loss: nan | e_stop: 0/30 | reg: nan | : 100%|█| 100/100 [00:55<00:00,  1.79it/

saving model version 0.1
iter: 36
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.98e+00 | tst_loss: 3.09e+00 | e_stop: 30/30 | reg: 4.00e+01 | :  58%|▌| 58/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 37
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.78e+00 | tst_loss: 3.10e+00 | e_stop: 30/30 | reg: 3.25e+01 | :  45%|▍| 45/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 38
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.44e+00 | e_stop: 30/30 | reg: 2.70e+01 | :  36%|▎| 36/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 39
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.02e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 3.14e+01 | :  42%|▍| 42/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 40
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.95e+00 | tst_loss: 3.06e+00 | e_stop: 0/30 | reg: 4.59e+01 | : 100%|█| 100/100 [00:51<

saving model version 0.1
iter: 41
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.82e+00 | tst_loss: 3.12e+00 | e_stop: 30/30 | reg: 3.22e+01 | :  32%|▎| 32/100 [00:17<

Early stopping criteria raised
saving model version 0.1
iter: 42
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.77e+00 | tst_loss: 3.03e+00 | e_stop: 30/30 | reg: 3.53e+01 | :  55%|▌| 55/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 43
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.12e+00 | e_stop: 30/30 | reg: 4.59e+01 | :  32%|▎| 32/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 44
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 2.86e+00 | e_stop: 30/30 | reg: 2.26e+01 | :  35%|▎| 35/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 45
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.86e+00 | tst_loss: 3.34e+00 | e_stop: 30/30 | reg: 2.78e+01 | :  40%|▍| 40/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 46
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 2.96e+00 | e_stop: 30/30 | reg: 2.92e+01 | :  61%|▌| 61/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 47
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.23e+00 | e_stop: 30/30 | reg: 5.01e+01 | :  68%|▋| 68/100 [00:34<

Early stopping criteria raised
saving model version 0.1
iter: 48
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 3.13e+00 | e_stop: 30/30 | reg: 3.19e+01 | :  60%|▌| 60/100 [00:31<

Early stopping criteria raised
saving model version 0.1
iter: 49
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.80e+00 | tst_loss: 3.15e+00 | e_stop: 30/30 | reg: 2.86e+01 | :  40%|▍| 40/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 50
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.26e+00 | e_stop: 30/30 | reg: 5.34e+01 | :  50%|▌| 50/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 51
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.98e+00 | tst_loss: 2.93e+00 | e_stop: 30/30 | reg: 3.12e+01 | :  38%|▍| 38/100 [00:12<

Early stopping criteria raised
saving model version 0.1
iter: 52
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.00e+00 | tst_loss: 2.74e+00 | e_stop: 30/30 | reg: 5.27e+01 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 53
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.82e+00 | tst_loss: 3.05e+00 | e_stop: 30/30 | reg: 3.31e+01 | :  36%|▎| 36/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 54
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.97e+00 | tst_loss: 2.85e+00 | e_stop: 30/30 | reg: 2.07e+01 | :  45%|▍| 45/100 [00:13<

Early stopping criteria raised
saving model version 0.1
iter: 55
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.27e+00 | e_stop: 30/30 | reg: 3.00e+01 | :  36%|▎| 36/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 56
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.97e+00 | tst_loss: 2.87e+00 | e_stop: 15/30 | reg: 5.15e+01 | : 100%|█| 100/100 [00:50

saving model version 0.1
iter: 57
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.83e+00 | tst_loss: 3.09e+00 | e_stop: 30/30 | reg: 2.46e+01 | :  55%|▌| 55/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 58
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.81e+00 | tst_loss: 3.13e+00 | e_stop: 30/30 | reg: 2.58e+01 | :  38%|▍| 38/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 59
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.88e+00 | tst_loss: 3.40e+00 | e_stop: 30/30 | reg: 4.12e+01 | :  62%|▌| 62/100 [00:31<

Early stopping criteria raised
saving model version 0.1
iter: 60
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.84e+00 | tst_loss: 3.14e+00 | e_stop: 30/30 | reg: 3.62e+01 | :  38%|▍| 38/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 61
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 2.71e+00 | e_stop: 8/30 | reg: 2.34e+01 | : 100%|█| 100/100 [00:51<

saving model version 0.1
iter: 62
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.83e+00 | tst_loss: 3.14e+00 | e_stop: 30/30 | reg: 3.10e+01 | :  46%|▍| 46/100 [00:24<

Early stopping criteria raised
saving model version 0.1
iter: 63
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.03e+00 | tst_loss: 3.08e+00 | e_stop: 21/30 | reg: 5.97e+01 | : 100%|█| 100/100 [00:52

saving model version 0.1
iter: 64
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 4.20e+01 | :  43%|▍| 43/100 [00:22<

Early stopping criteria raised
saving model version 0.1
iter: 65
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.22e+00 | e_stop: 30/30 | reg: 3.11e+01 | :  43%|▍| 43/100 [00:23<

Early stopping criteria raised
saving model version 0.1
iter: 66
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.84e+00 | tst_loss: 3.29e+00 | e_stop: 30/30 | reg: 2.43e+01 | :  40%|▍| 40/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 67
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.98e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 2.33e+01 | :  35%|▎| 35/100 [00:11<

Early stopping criteria raised
saving model version 0.1
iter: 68
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 3.55e+00 | e_stop: 30/30 | reg: 3.71e+01 | :  36%|▎| 36/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 69
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.77e+00 | tst_loss: 3.46e+00 | e_stop: 30/30 | reg: 3.36e+01 | :  36%|▎| 36/100 [00:19<

Early stopping criteria raised
saving model version 0.1
iter: 70
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.93e+00 | tst_loss: 3.15e+00 | e_stop: 30/30 | reg: 2.66e+01 | :  38%|▍| 38/100 [00:10<

Early stopping criteria raised
saving model version 0.1
iter: 71
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.99e+00 | tst_loss: 3.30e+00 | e_stop: 30/30 | reg: 3.73e+01 | :  54%|▌| 54/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 72
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.98e+00 | tst_loss: 2.78e+00 | e_stop: 30/30 | reg: 3.32e+01 | :  54%|▌| 54/100 [00:28<

Early stopping criteria raised
saving model version 0.1
iter: 73
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.82e+00 | tst_loss: 3.12e+00 | e_stop: 30/30 | reg: 3.71e+01 | :  48%|▍| 48/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 74
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.91e+00 | tst_loss: 2.70e+00 | e_stop: 30/30 | reg: 2.85e+01 | :  75%|▊| 75/100 [00:41<

Early stopping criteria raised
saving model version 0.1
iter: 75
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.81e+00 | tst_loss: 3.06e+00 | e_stop: 30/30 | reg: 3.31e+01 | :  64%|▋| 64/100 [00:32<

Early stopping criteria raised
saving model version 0.1
iter: 76
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.94e+00 | tst_loss: 3.05e+00 | e_stop: 30/30 | reg: 2.01e+01 | :  37%|▎| 37/100 [00:14<

Early stopping criteria raised
saving model version 0.1
iter: 77
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.73e+00 | tst_loss: 3.33e+00 | e_stop: 30/30 | reg: 3.92e+01 | :  54%|▌| 54/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 78
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 3.06e+00 | tst_loss: 3.07e+00 | e_stop: 30/30 | reg: 3.28e+01 | :  34%|▎| 34/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 79
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.82e+00 | tst_loss: 3.03e+00 | e_stop: 30/30 | reg: 4.37e+01 | :  40%|▍| 40/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 80
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.84e+00 | tst_loss: 2.60e+00 | e_stop: 30/30 | reg: 3.20e+01 | :  54%|▌| 54/100 [00:27<

Early stopping criteria raised
saving model version 0.1
iter: 81
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 3.08e+00 | e_stop: 30/30 | reg: 3.67e+01 | :  75%|▊| 75/100 [00:38<

Early stopping criteria raised
saving model version 0.1
iter: 82
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.80e+00 | tst_loss: 3.33e+00 | e_stop: 30/30 | reg: 3.69e+01 | :  37%|▎| 37/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 83
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.79e+00 | tst_loss: 3.04e+00 | e_stop: 30/30 | reg: 3.48e+01 | :  61%|▌| 61/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 84
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 2.95e+00 | e_stop: 8/30 | reg: 2.77e+01 | : 100%|█| 100/100 [00:48<

saving model version 0.1
iter: 85
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.77e+00 | tst_loss: 2.94e+00 | e_stop: 30/30 | reg: 3.46e+01 | :  51%|▌| 51/100 [00:25<

Early stopping criteria raised
saving model version 0.1
iter: 86
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.86e+00 | tst_loss: 2.90e+00 | e_stop: 30/30 | reg: 3.63e+01 | :  50%|▌| 50/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 87
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.89e+00 | tst_loss: 3.21e+00 | e_stop: 30/30 | reg: 3.90e+01 | :  61%|▌| 61/100 [00:31<

Early stopping criteria raised
saving model version 0.1
iter: 88
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.90e+00 | tst_loss: 3.27e+00 | e_stop: 30/30 | reg: 2.34e+01 | :  45%|▍| 45/100 [00:16<

Early stopping criteria raised
saving model version 0.1
iter: 89
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.79e+00 | tst_loss: 3.35e+00 | e_stop: 30/30 | reg: 3.56e+01 | :  36%|▎| 36/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 90
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 2.93e+00 | e_stop: 30/30 | reg: 5.33e+01 | :  59%|▌| 59/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 91
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.75e+00 | tst_loss: 3.26e+00 | e_stop: 30/30 | reg: 3.52e+01 | :  39%|▍| 39/100 [00:20<

Early stopping criteria raised
saving model version 0.1
iter: 92
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.77e+00 | tst_loss: 3.30e+00 | e_stop: 30/30 | reg: 3.71e+01 | :  35%|▎| 35/100 [00:18<

Early stopping criteria raised
saving model version 0.1
iter: 93
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.85e+00 | tst_loss: 3.10e+00 | e_stop: 30/30 | reg: 3.02e+01 | :  50%|▌| 50/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 94
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.76e+00 | tst_loss: 3.12e+00 | e_stop: 30/30 | reg: 3.69e+01 | :  60%|▌| 60/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 95
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.83e+00 | tst_loss: 2.84e+00 | e_stop: 30/30 | reg: 2.41e+01 | :  52%|▌| 52/100 [00:26<

Early stopping criteria raised
saving model version 0.1
iter: 96
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 3.10e+00 | e_stop: 30/30 | reg: 5.00e+01 | :  90%|▉| 90/100 [00:46<

Early stopping criteria raised
saving model version 0.1
iter: 97
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.92e+00 | tst_loss: 3.00e+00 | e_stop: 30/30 | reg: 3.68e+01 | :  41%|▍| 41/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 98
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.82e+00 | tst_loss: 3.28e+00 | e_stop: 30/30 | reg: 3.71e+01 | :  60%|▌| 60/100 [00:30<

Early stopping criteria raised
saving model version 0.1
iter: 99
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.78e+00 | tst_loss: 2.94e+00 | e_stop: 30/30 | reg: 4.01e+01 | :  41%|▍| 41/100 [00:21<

Early stopping criteria raised
saving model version 0.1
iter: 100
checkpoint directory created: ./model
saving model version 0.0

| trn_loss: 2.94e+00 | tst_loss: 3.12e+00 | e_stop: 30/30 | reg: 3.98e+01 | :  47%|▍| 47/100 [00:24<

Early stopping criteria raised
saving model version 0.1
-------

In [7]:
full_df

        alg_name  iter       rmse        r2       mae
0         MLP_Cr     1   0.195370  0.912368  0.358914
1         MLP_Cr     2   0.203058  0.918579  0.354085
2         MLP_Cr     3   0.242216  0.903074  0.383426
3         MLP_Cr     4   0.230227  0.911457  0.399531
4         MLP_Cr     5   0.220583  0.907901  0.382985
...          ...   ...        ...       ...       ...
1195  lmdKAN_NO3    96  10.993112  0.763023  2.836856
1196  lmdKAN_NO3    97  10.271236  0.778028  2.771183
1197  lmdKAN_NO3    98   9.526242  0.783016  2.537381
1198  lmdKAN_NO3    99   9.067707  0.778079  2.515548
1199  lmdKAN_NO3   100   8.960998  0.763910  2.487845

[1200 rows x 5 columns]

In [8]:
full_df.to_excel(f'Accuracy_metrics.xlsx')
#pd.read_excel('full_metrics.xlsx').drop('Unnamed: 0', axis=1)

In [ ]:
aggr_df = full_df.groupby(['alg_name']).agg(["mean", "std"]).drop(['iter'], axis=1)
aggr_df.to_excel(f'aggr_Accuracy_metrics.xlsx')
aggr_df

                rmse                  r2                 mae
                mean       std      mean       std      mean       std
alg_name
KAN_Cr      0.151094  0.118393  0.939226  0.047426  0.275843  0.081338
KAN_Cu      0.588070  0.160172  0.759886  0.068476  0.569367  0.074292
KAN_NO3     9.127693  1.149694  0.784641  0.031634  2.537344  0.192192
KAN_Ni      2.381816  0.270567  0.036730  0.060717  1.319784  0.094479
MLP_Cr      0.202864  0.029077  0.918372  0.011374  0.359317  0.027571
MLP_Cu      0.633501  0.115562  0.741906  0.048335  0.601832  0.063553
MLP_NO3     9.667228  1.234268  0.772611  0.028910  2.589856  0.193319
MLP_Ni      2.352136  0.252780  0.048711  0.051488  1.319042  0.088436
lmdKAN_Cr   0.161150  0.036202  0.935181  0.014367  0.303765  0.036234
lmdKAN_Cu   0.582567  0.107578  0.762585  0.044511  0.574617  0.054079
lmdKAN_NO3  9.748527  1.202873  0.769885  0.034123  2.610525  0.193037
lmdKAN_Ni   2.485714  0.368029 -0.004646  0.110744  1.351495  0.096215

In [11]:
aggr_df.to_excel(f'aggr_Accuracy_metrics.xlsx')